param(
  [string]$FixturePath,
  [string]$ReportPath,
  [string]$WorkRoot
)

$ErrorActionPreference='Stop'
$projectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
if([string]::IsNullOrWhiteSpace($FixturePath)){$FixturePath=Join-Path $projectRoot 'examples/joint-visual-revision-fixtures/fixtures.json'}
if([string]::IsNullOrWhiteSpace($ReportPath)){$ReportPath=Join-Path $projectRoot 'state/checks/joint-visual-revision-contract-report.json'}
if([string]::IsNullOrWhiteSpace($WorkRoot)){$WorkRoot=Join-Path $projectRoot 'state/checks/joint-visual-revision-work'}

. (Join-Path $PSScriptRoot 'R7ContractHelper.ps1')
. (Join-Path $PSScriptRoot 'R6ContentEvidenceRuntime.ps1')
. (Join-Path $PSScriptRoot 'R3VisualNeed.ps1')
. (Join-Path $PSScriptRoot 'R7SemanticRuntime.ps1')
. (Join-Path $PSScriptRoot 'R7HumanRevisionRuntime.ps1')

$fixture=Get-Content -LiteralPath $FixturePath -Raw -Encoding UTF8|ConvertFrom-Json
$cases=[Collections.Generic.List[object]]::new()
function Add-Case([string]$Id,[bool]$Passed,[string[]]$Evidence){$script:cases.Add([ordered]@{case_id=$Id;status=$(if($Passed){'pass'}else{'fail'});evidence=[object[]]$Evidence})}

$schemaPaths=@(
  'templates/schema/r6/news-evidence-pip.v0.2.schema.json','templates/schema/r3/visual-need-analysis.v0.5.schema.json','templates/schema/r3/visual-coverage-ledger.v0.2.schema.json','templates/schema/r3/visual-source-routing.v0.1.schema.json','templates/schema/r3/asset-reuse-authorization.v0.1.schema.json','templates/schema/r7/visual-analysis-package.v0.2.schema.json','templates/schema/r7/image-asset-set.v0.2.schema.json','templates/schema/r7/delivery-revision-request.v0.1.schema.json','templates/schema/r7/workflow-session-record.v0.2.schema.json','templates/schema/r7/semantic-task-envelope.v0.3.schema.json','templates/schema/r7/compatibility-matrix.v0.3.schema.json','templates/schema/p0/session-execution-plan.v0.9.schema.json','templates/schema/final-delivery/typed-components.v0.8.schema.json','templates/schema/final-delivery/final-delivery.v0.8.schema.json'
)
$schemaErrors=[Collections.Generic.List[string]]::new();foreach($relative in $schemaPaths){try{[void](Get-Content -LiteralPath (Join-Path $projectRoot $relative) -Raw -Encoding UTF8|ConvertFrom-Json)}catch{$schemaErrors.Add("${relative}:$($_.Exception.Message)")}}
Add-Case 'schema_set_parse' ($schemaErrors.Count-eq0) $schemaErrors.ToArray()
$matrix=Get-Content -LiteralPath (Join-Path $projectRoot 'templates/schema/r7/compatibility-matrix.v0.3.json') -Raw -Encoding UTF8|ConvertFrom-Json
$matrixEntries=@($matrix.entries);$currentDirect=@($matrixEntries|Where-Object{$_.workflow_contract-eq'direct_delivery_single_v0.3'});$currentHotspot=@($matrixEntries|Where-Object{$_.workflow_contract-eq'hotspot_to_delivery_single_v0.3'});$historicalDirect=@($matrixEntries|Where-Object{$_.workflow_contract-eq'direct_delivery_single_v0.2'});$historicalHotspot=@($matrixEntries|Where-Object{$_.workflow_contract-eq'hotspot_to_delivery_single_v0.2'})
Add-Case 'compatibility_matrix_current_and_history' ($matrix.matrix_version-eq'0.3'-and$currentDirect.Count-eq1-and$currentHotspot.Count-eq1-and$currentDirect[0].plan_contract-eq'p0-session-execution-plan-v0.9'-and$currentHotspot[0].delivery_contract-eq'p0-delivery-v0.8'-and$historicalDirect[0].resume_status-eq'replay_only'-and$historicalHotspot[0].resume_status-eq'replay_only') @()

$evidenceErrors=@(Test-R6EvidenceBundleV02 $fixture.evidence_bundle)
Add-Case 'r6_evidence_anchor_positive' ($evidenceErrors.Count-eq0) $evidenceErrors
$mismatch=$fixture.evidence_bundle|ConvertTo-Json -Depth 50|ConvertFrom-Json;$mismatch.semantic_fact_bindings[0].comparison_result='mismatch';$mismatch.semantic_parity_result='match'
$mismatchErrors=@(Test-R6EvidenceBundleV02 $mismatch);Add-Case 'r6_parity_precedence_negative' ($mismatchErrors-contains'semantic_parity_precedence_mismatch') $mismatchErrors
$notAssessed=$fixture.evidence_bundle|ConvertTo-Json -Depth 50|ConvertFrom-Json;$notAssessed.semantic_fact_bindings[0].comparison_result='not_assessed';$notAssessed.semantic_parity_result='not_assessed'
$notAssessedErrors=@(Test-R6EvidenceBundleV02 $notAssessed);Add-Case 'r6_not_assessed_blocks_render' ($notAssessedErrors-contains'semantic_parity_blocker_bypassed') $notAssessedErrors
$ocr=$fixture.evidence_bundle|ConvertTo-Json -Depth 50|ConvertFrom-Json;$ocr.evidence_anchor_annotation.visible_quote.extraction_method='ocr';$ocr.semantic_fact_bindings[0].visual_review_ref=$null
$ocrErrors=@(Test-R6EvidenceBundleV02 $ocr);Add-Case 'r6_ocr_requires_visual_review' ($ocrErrors-contains'semantic_fact_ocr_review_required:FACT-DATE-001') $ocrErrors
$integration=Test-R6EvidenceBundle $fixture.evidence_bundle;Add-Case 'r6_runtime_dispatch_v02' ($integration.status-eq'pass') @($integration.errors)

$routeErrors=[Collections.Generic.List[string]]::new();foreach($task in @($fixture.visual_routes.tasks)){$authorization=if($task.source_class-eq'explicit_existing_asset'){$fixture.visual_routes.reuse_authorization}else{$null};foreach($e in(Test-R3VisualTaskSourceRouteV01 $task ([string]$fixture.visual_routes.test_profile) $authorization ([string]$fixture.visual_routes.session_id) ([string]$fixture.visual_routes.account_snapshot_id))){$routeErrors.Add("$($task.visual_task_id):$e")}}
Add-Case 'r3_exclusive_routes_positive' ($routeErrors.Count-eq0) $routeErrors.ToArray()
$deterministic=$fixture.visual_routes.tasks[2]|ConvertTo-Json -Depth 30|ConvertFrom-Json;$deterministic.disposition='create_deterministic_visual';$deterministic.production_path='deterministic_render'
$deterministicErrors=@(Test-R3VisualTaskSourceRouteV01 $deterministic 'production');Add-Case 'r3_deterministic_primary_rejected' ($deterministicErrors-contains'deterministic_primary_visual_forbidden') $deterministicErrors
$badAuth=$fixture.visual_routes.reuse_authorization|ConvertTo-Json -Depth 30|ConvertFrom-Json;$badAuth.scope='all_future_sessions'
$authErrors=@(Test-R3VisualTaskSourceRouteV01 $fixture.visual_routes.tasks[1] 'production' $badAuth ([string]$fixture.visual_routes.session_id) ([string]$fixture.visual_routes.account_snapshot_id));Add-Case 'r3_reuse_scope_negative' ($authErrors-contains'asset_reuse_authorization_wildcard_forbidden') $authErrors
$noProvider=$fixture.visual_routes.tasks[2]|ConvertTo-Json -Depth 30|ConvertFrom-Json;$noProvider.task_status='materialized'
$profileErrors=@(Test-R3VisualTaskSourceRouteV01 $noProvider 'no_provider');Add-Case 'r3_test_profile_waits_assets' ($profileErrors-contains'test_profile_generated_context_must_wait_assets') $profileErrors
$r3Source=Get-Content -LiteralPath (Join-Path $projectRoot 'tools/R3VisualNeed.ps1') -Raw -Encoding UTF8;Add-Case 'r3_v05_runtime_wired' ($r3Source.Contains('visual-need-analysis/v0.5')-and$r3Source.Contains('Test-R3VisualTaskSourceRouteV01')) @()

$registries=Get-R7RuntimeRegistries $projectRoot;$plan=New-R7RuntimePlan 'SESSION-JOINT-001' 'direct_delivery_single_v0.3' $registries 'production';$planErrors=@(Test-P0PlanContract $plan)
Add-Case 'r7_v09_plan_positive' ($planErrors.Count-eq0) $planErrors
$nodeOrder=@($plan.steps|Where-Object{$_.node_id-ne'session_plan'}|ForEach-Object{[string]$_.node_id});$sourceMap=@($fixture.revision.source_map);$sourceMapRef=[ordered]@{artifact_id='FD-SESSION-JOINT-001-001:source-map';sha256='sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'}
function New-FixtureRequest([object[]]$RawItems){$items=[Collections.Generic.List[object]]::new();$n=0;foreach($raw in $RawItems){$n++;$source=@($sourceMap|Where-Object{$_.artifact_id-eq$raw.target_artifact_id})|Select-Object -First 1;$owner=Get-R7RevisionOwnerNode ([string]$raw.change_class) ([string]$plan.blueprint_id);$items.Add([ordered]@{change_item_id="CHANGE-$n";target_ref=[ordered]@{artifact_id=[string]$source.artifact_id;artifact_type=[string]$source.artifact_type};target_sha256=[string]$source.sha256;change_class=[string]$raw.change_class;original_instruction=[string]$raw.instruction;normalized_instruction=[string]$raw.instruction;owning_producer=$owner;candidate_source_map_ref=$sourceMapRef})};$restart=Get-R7RevisionRestartNode @($items) ([string[]]$nodeOrder);$restartIndex=[Array]::IndexOf([string[]]$nodeOrder,$restart);$invalidated=@($sourceMap|Where-Object{$node=Get-R7RevisionArtifactNode ([string]$_.artifact_type) ([string]$plan.blueprint_id);[Array]::IndexOf([string[]]$nodeOrder,[string]$node)-ge$restartIndex}|ForEach-Object{[ordered]@{artifact_id=$_.artifact_id;sha256=$_.sha256}});$carried=@($sourceMap|Where-Object{$node=Get-R7RevisionArtifactNode ([string]$_.artifact_type) ([string]$plan.blueprint_id);[Array]::IndexOf([string[]]$nodeOrder,[string]$node)-lt$restartIndex}|ForEach-Object{[ordered]@{artifact_id=$_.artifact_id;sha256=$_.sha256}});return [pscustomobject]@{schema_id='taoge://schemas/r7/delivery-revision-request/v0.1';schema_version='0.1.0';revision_request_id='DREQ-SESSION-JOINT-001-002';request_revision=2;session_id='SESSION-JOINT-001';current_delivery_ref=[ordered]@{artifact_id='DELIVERY-001';sha256='sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'};current_candidate_ref=[ordered]@{artifact_id='FD-001';sha256='sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc'};candidate_source_map_ref=$sourceMapRef;source_plan_ref=[ordered]@{artifact_id=$plan.plan_id;sha256='sha256:dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd'};user_instruction='Revise the selected delivery targets.';normalized_action='revise_delivery';change_items=[object[]]$items.ToArray();restart_from_node_id=$restart;invalidated_artifact_refs=[object[]]$invalidated;carried_forward_artifact_refs=[object[]]$carried;request_digest='sha256:eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee';request_status='active';created_by='human';created_at='2026-07-15T00:00:00Z'}}
$single=New-FixtureRequest @($fixture.revision.single_change);$singleErrors=@(Test-R7DeliveryRevisionRequestV01 $single $sourceMap ([string[]]$nodeOrder));Add-Case 'r7_single_target_request' ($singleErrors.Count-eq0-and$single.restart_from_node_id-eq'cover_design') $singleErrors
$multi=New-FixtureRequest @($fixture.revision.multi_change);$multiErrors=@(Test-R7DeliveryRevisionRequestV01 $multi $sourceMap ([string[]]$nodeOrder));$invalidIds=@($multi.invalidated_artifact_refs|ForEach-Object{[string]$_.artifact_id});Add-Case 'r7_multi_target_earliest_union' ($multiErrors.Count-eq0-and$multi.restart_from_node_id-eq'visual_need_analysis'-and'LEDGER-001'-in$invalidIds-and'ASSETSET-001'-in$invalidIds-and'COVER-001'-in$invalidIds) $multiErrors
$replan=New-R7HumanRevisionPlan $plan $multi;$replanErrors=@(Test-P0PlanContract $replan);$branchFirst=@($replan.steps|Where-Object{$_.step_id-like'*-R2'}|Select-Object -First 1);Add-Case 'r7_replan_nonterminal_branch' ($replanErrors.Count-eq0-and$replan.plan_revision-eq2-and$branchFirst.node_id-eq'visual_need_analysis'-and$replan.steps[-1].node_id-eq'final_human_gate') $replanErrors
$duplicate=$multi|ConvertTo-Json -Depth 50|ConvertFrom-Json;$duplicate.change_items+=@($duplicate.change_items[0]);$duplicateErrors=@(Test-R7DeliveryRevisionRequestV01 $duplicate $sourceMap ([string[]]$nodeOrder));Add-Case 'r7_duplicate_target_negative' (@($duplicateErrors|Where-Object{$_-like'delivery_revision_item_duplicate:*'}).Count-gt0) $duplicateErrors
$unknown=$single|ConvertTo-Json -Depth 50|ConvertFrom-Json;$unknown.change_items[0].target_ref.artifact_id='UNKNOWN-001';$unknownErrors=@(Test-R7DeliveryRevisionRequestV01 $unknown $sourceMap ([string[]]$nodeOrder));Add-Case 'r7_unknown_target_negative' ($unknownErrors-contains'delivery_revision_target_not_current:UNKNOWN-001') $unknownErrors
$runtimeSession=Join-Path $WorkRoot ('runtime-'+[guid]::NewGuid().ToString('N').Substring(0,8));[void][IO.Directory]::CreateDirectory($runtimeSession)
$initialize=Initialize-R7RuntimeSession $projectRoot $runtimeSession 'direct_delivery_single_v0.3' 'no_provider';$runtimePlan=Read-P0JsonFile (Join-Path $runtimeSession 'intermediate/p0/session-execution-plan.json');$eventPath=Join-Path $runtimeSession 'intermediate/p0/execution-events.jsonl';$runtimeErrors=[Collections.Generic.List[string]]::new()
if($initialize.ExitCode-ne0){$runtimeErrors.Add('runtime_initialize_failed:'+$initialize.ResultCode)}
foreach($step in @($runtimePlan.steps|Where-Object{$_.node_id-ne'session_plan'-and$_.node_id-ne'final_human_gate'})){$source=switch([string]$step.step_kind){'deterministic_tool'{'runner'}'agent_required'{'agent_recorder'}'human_gate'{'human_recorder'}'external_side_effect'{'external_recorder'}default{'runner'}};$eventCount=@(Get-P0EvidenceEvents $eventPath).Count;$write=Write-P0EvidenceEvent -EventPath $eventPath -Plan $runtimePlan -StepId ([string]$step.step_id) -EventType 'step.completed.v1' -EventSource $source -StateBefore 'ready' -StateAfter 'succeeded' -PayloadDigest 'sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' -IdempotencyKey ("fixture:"+[string]$step.step_id) -ExpectedLastSequenceNo $eventCount -ResultCode 'fixture_completed' -SafeSummary 'Joint revision executable fixture prerequisite completed' -InputDigest 'sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb' -ExecutionAttemptId ("ATT-"+[string]$step.step_id);if($write.ExitCode-ne0){$runtimeErrors.Add("event_write_failed:$($step.step_id):$($write.ResultCode)")}}
$runtimeProjection=Update-P0StateProjection $runtimeSession $runtimePlan $eventPath $false;if($runtimeProjection.ExitCode-ne0-or[string]$runtimeProjection.Projection.next_step_id-notlike'*-final_human_gate'){$runtimeErrors.Add('runtime_final_human_projection_missing')}
$taskId='TASK-JOINT-FINAL';$taskPath=Resolve-R7RuntimePath $runtimeSession "intermediate/r7/tasks/$taskId.json";Write-P0EvidenceAtomicText $taskPath (ConvertTo-P0EvidenceJsonText ([ordered]@{task_envelope_id=$taskId;node_id='final_human_gate'}))
function Write-JointCurrentArtifact([string]$Type,[string]$Id,[object]$Payload){$relative="intermediate/r7/revisions/$Type/$Id.json";$path=Resolve-R7RuntimePath $runtimeSession $relative;Write-P0EvidenceAtomicText $path (ConvertTo-P0EvidenceJsonText $Payload);$pointer=[ordered]@{artifact_type=$Type;artifact_id=$Id;revision=1;revision_path=$relative;sha256=Get-R7RuntimeHash $path;status='completed'};Write-P0EvidenceAtomicText (Resolve-R7RuntimePath $runtimeSession "intermediate/r7/current/$Type.json") (ConvertTo-P0EvidenceJsonText $pointer)}
Write-JointCurrentArtifact 'final_delivery_render_candidate' 'FD-JOINT-001' ([ordered]@{final_delivery_id='FD-JOINT-001';source_map=[object[]]$sourceMap})
Write-JointCurrentArtifact 'final_delivery' 'DELIVERY-JOINT-001' ([ordered]@{delivery_id='DELIVERY-JOINT-001'})
Write-JointCurrentArtifact 'viewport_acceptance_report' 'VIEWPORT-JOINT-001' ([ordered]@{report_id='VIEWPORT-JOINT-001'})
$changePath=Join-Path $runtimeSession 'change-items.json';Write-P0EvidenceAtomicText $changePath (ConvertTo-P0EvidenceJsonText ([ordered]@{user_instruction='Revise the selected delivery targets.';change_items=[object[]]$fixture.revision.multi_change}))
$runtimeRevision=Invoke-R7HumanRevisionRequest $projectRoot $runtimeSession $taskId $changePath '';$runtimePlanV2=Read-P0JsonFile (Join-Path $runtimeSession 'intermediate/p0/session-execution-plan.json');$runtimeProjectionV2=Read-P0JsonFile (Join-Path $runtimeSession 'intermediate/p0/state-projection.json');$requestPointerPath=Resolve-R7RuntimePath $runtimeSession 'intermediate/r7/current/delivery_revision_request.json';$requestPointer=if(Test-Path -LiteralPath $requestPointerPath){Read-R7JsonFile $requestPointerPath}else{$null}
if($runtimeRevision.ExitCode-ne0){$runtimeErrors.Add('revision_runtime_failed:'+[string]$runtimeRevision.ResultCode)}
if([int]$runtimePlanV2.plan_revision-ne2-or[string]$runtimePlanV2.restart_from_node_id-ne'visual_need_analysis'){$runtimeErrors.Add('revision_runtime_plan_v2_invalid')}
if([string]$runtimeProjectionV2.current_state-eq'completed'-or[string]::IsNullOrWhiteSpace([string]$runtimeProjectionV2.next_step_id)-or[string]$runtimeProjectionV2.next_step_id-notlike'*-visual_need_analysis-R2'){$runtimeErrors.Add('revision_runtime_nonterminal_projection_invalid')}
if($null-eq$requestPointer-or[string]$requestPointer.status-ne'active'){$runtimeErrors.Add('revision_runtime_pointer_missing')}
Add-Case 'r7_revision_runtime_filesystem' ($runtimeErrors.Count-eq0) $runtimeErrors.ToArray()
$duplicateRuntime=Invoke-R7HumanRevisionRequest $projectRoot $runtimeSession $taskId $changePath ''
Add-Case 'r7_revision_duplicate_reused_runtime' ($duplicateRuntime.ExitCode-eq0-and$duplicateRuntime.ResultCode-eq'duplicate_reused') @([string]$duplicateRuntime.ResultCode)
$conflictRuntime=Invoke-R7HumanRevisionRequest $projectRoot $runtimeSession $taskId $changePath 'Different active revision instruction.'
Add-Case 'r7_revision_single_active_runtime' ($conflictRuntime.ExitCode-eq1-and$conflictRuntime.ResultCode-eq'active_delivery_revision_request_exists') @([string]$conflictRuntime.ResultCode)
$humanSource=Get-Content -LiteralPath (Join-Path $projectRoot 'tools/R7HumanRevisionRuntime.ps1') -Raw -Encoding UTF8;$candidateSource=Get-Content -LiteralPath (Join-Path $projectRoot 'tools/R7CandidateRuntime.ps1') -Raw -Encoding UTF8;$viewportSource=Get-Content -LiteralPath (Join-Path $projectRoot 'tools/R7ViewportRuntime.ps1') -Raw -Encoding UTF8
foreach($caseId in @($fixture.revision.required_cases)){$passed=switch($caseId){'single_target'{$true}'multi_target_earliest_restart'{$true}'invalidation_union'{$true}'duplicate_target_rejected'{$true}'unknown_target_rejected'{$true}'concurrent_active_request_blocked'{$conflictRuntime.ResultCode-eq'active_delivery_revision_request_exists'}'duplicate_request_reconciled'{$duplicateRuntime.ResultCode-eq'duplicate_reused'}'producer_interruption_recoverable'{$humanSource.Contains('plan-commits')-and$humanSource.Contains('basis_revision_request_ref')}'pointer_last'{$null-ne$requestPointer-and(Test-Path -LiteralPath (Resolve-R7RuntimePath $runtimeSession ([string]$requestPointer.revision_path)))}'old_html_preserved'{$candidateSource.Contains('deliverables/revisions/r')}'second_viewport'{$viewportSource.Contains('Complete-R7ActiveRevisionRequest')}'second_human_gate'{$replan.steps[-1].node_id-eq'final_human_gate'}default{$false}};Add-Case "fixture_$caseId" $passed @()}

$failed=@($cases|Where-Object{$_.status-ne'pass'});$report=[ordered]@{schema_id='taoge://reports/joint-visual-revision-contract/v0.1';generated_at=[DateTimeOffset]::UtcNow.ToString('o');fixture_version=[string]$fixture.fixture_version;status=$(if($failed.Count){'fail'}else{'pass'});case_count=$cases.Count;failed_count=$failed.Count;cases=[object[]]$cases.ToArray()}
$directory=Split-Path -Parent $ReportPath;if(-not(Test-Path -LiteralPath $directory)){[IO.Directory]::CreateDirectory($directory)|Out-Null};$utf8=[Text.UTF8Encoding]::new($false);[IO.File]::WriteAllText($ReportPath,($report|ConvertTo-Json -Depth 60),$utf8)
$report|ConvertTo-Json -Depth 60
Write-Output "JOINT_VISUAL_REVISION_CHECK=$(if($failed.Count){'fail'}else{'pass'})"
Write-Output "JOINT_VISUAL_REVISION_CASE_COUNT=$($cases.Count)"
Write-Output "JOINT_VISUAL_REVISION_FAILURE_COUNT=$($failed.Count)"
if($failed.Count){exit 1};exit 0
