param(
  [string]$WorkRoot='state/checks/r7-h6a-hotspot-work',
  [string]$HumanReportPath='state/checks/r7-h6a-hotspot-report.md',
  [string]$MachineReportPath='state/checks/r7-h6a-hotspot-report.json'
)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'WindowsRuntimeHelper.ps1')
. (Join-Path $PSScriptRoot 'R7ContractHelper.ps1')
. (Join-Path $PSScriptRoot 'R7SemanticRuntime.ps1')
. (Join-Path $PSScriptRoot 'R7CandidateRuntime.ps1')
. (Join-Path $PSScriptRoot 'R7HotspotContractHelper.ps1')
. (Join-Path $PSScriptRoot 'R7HotspotRuntime.ps1')

function Resolve-H6APath([string]$Path){if([IO.Path]::IsPathRooted($Path)){return [IO.Path]::GetFullPath($Path)};return [IO.Path]::GetFullPath((Join-Path $script:ProjectRoot $Path))}
function Copy-H6AObject([object]$Value){return ($Value|ConvertTo-Json -Depth 90|ConvertFrom-Json)}
function New-H6AResult([string]$Id,[bool]$Passed,[string]$Actual,[string[]]$Errors=@()){return [pscustomobject]@{fixture_id=$Id;expected_result='pass';actual_result=$(if($Passed){'pass'}else{$Actual});expectation_met=$Passed;errors=[object[]]@($Errors)}}
function Add-H6AResult([Collections.Generic.List[object]]$Results,[string]$Id,[bool]$Passed,[string]$Actual,[string[]]$Errors=@()){$Results.Add((New-H6AResult $Id $Passed $Actual $Errors))}
function Write-H6AJson([string]$Path,[object]$Value){Write-P0EvidenceAtomicText $Path (ConvertTo-P0EvidenceJsonText $Value)}

function New-H6AResearchSet {
  param([object]$RequestItem,[switch]$NoRecommendation,[switch]$HighRisk)
  $event=[ordered]@{event_id='EVT-H6A-001';subject='used vehicle dealer';action='announced a verified operating change';time_boundary='2026-07';event_fingerprint='used-vehicle-dealer-change'}
  $candidate=[ordered]@{candidate_id='CAND-H6A-001';event_id='EVT-H6A-001';account_relevance='direct_used_vehicle';ranking_status='ranked_by_r5';spillover_used=$false}
  $source1=[ordered]@{source_record_id='SRC-H6A-001';source_identity='official-primary';canonical_url='https://example.invalid/official';published_at='2026-07-15T00:00:00Z';observed_at='2026-07-15T01:00:00Z';capture_availability='available'}
  $source2=[ordered]@{source_record_id='SRC-H6A-002';source_identity='independent-secondary';canonical_url='https://example.invalid/secondary';published_at='2026-07-15T00:10:00Z';observed_at='2026-07-15T01:00:00Z';capture_availability='available'}
  $claim=[ordered]@{claim_id='CLM-H6A-001';claim_type='factual_claim';claim_evidence_status='supported';source_record_ids=@('SRC-H6A-001');source_independence_status='single_source';source_support_basis='authoritative_primary';allowed_expression=$(if($HighRisk){'attribute_to_source'}else{'assert_as_fact'})}
  $packet=[ordered]@{topic_evidence_packet_id='EVID-H6A-001';event_fact_status='verified';propagation_status='observed';risk_level=$(if($HighRisk){'high'}else{'medium'});claims=@($claim);impact_chain=@('dealer operation','consumer decision')}
  $topic=[ordered]@{topic_option_id='TOPIC-H6A-001';topic_identity='used-vehicle-dealer-change';title='What this operating change means';event_id='EVT-H6A-001';candidate_id='CAND-H6A-001';topic_evidence_packet_id='EVID-H6A-001';audience='used vehicle buyers and dealers';impact_chain=@('operating change','market effect','audience action');topic_status='topic_pending_human_choice'}
  $map=[ordered]@{};foreach($pair in @(@('EVT-H6A-001',$event),@('CAND-H6A-001',$candidate),@('EVID-H6A-001',$packet),@('SRC-H6A-001',$source1),@('SRC-H6A-002',$source2),@('TOPIC-H6A-001',$topic))){$map[$pair[0]]=Get-R7HotspotCanonicalDigest $pair[1]}
  $localTopicRef=[ordered]@{component_type='topic_option';component_id='TOPIC-H6A-001';component_sha256=$map['TOPIC-H6A-001']};[object[]]$topics=@();[object[]]$ordered=@();$recommended=$null;if(-not$NoRecommendation){$topics=@($topic);$ordered=@($localTopicRef);$recommended=$localTopicRef}
  return [pscustomobject]@{schema_id='taoge://schemas/r7/hotspot-research-set/v0.1';schema_version='0.1.0';research_set_id='HRS-H6A-001';research_set_revision=1;account_identity_ref=$RequestItem.Payload.account_identity_ref;account_snapshot_ref=$RequestItem.Payload.account_snapshot_ref;radar_policy_ref=$RequestItem.Payload.radar_policy_ref;research_request_ref=$RequestItem.Ref;research_run_record=[ordered]@{research_run_id='RUN-H6A-001';direct_used_vehicle_verified_count=1;spillover_activation_status='consumed_from_r5';ranking_owner='r5'};signals=@();events=@($event);candidates=@($candidate);topic_options=[object[]]$topics;topic_evidence_packets=@($packet);panel_model=[ordered]@{ordered_topic_option_refs=[object[]]$ordered;recommended_topic_ref=$recommended;recommendation_reason=$(if($NoRecommendation){'No verified selectable topic was found.'}else{'Highest account relevance under the R5 ranking.'})};source_records=@($source1,$source2);ledger_write_refs=@();component_digest_map=$map;researched_at='2026-07-15T01:00:00Z';research_set_status=$(if($NoRecommendation){'ready_no_recommendation'}else{'ready_for_panel'})}
}

function Invoke-H6ASemanticCommit {
  param([string]$Session,[object]$Payload,[string]$Status,[string]$PayloadName)
  $prepared=Prepare-R7RuntimeTask $script:ProjectRoot $Session;if($prepared.ExitCode-ne0){throw "prepare_failed:$($prepared.ResultCode):$([string]::Join(';',@($prepared.Errors)))"};if([string]$prepared.Data.Task.action_registry_version-ne'r7-action-registry-v0.2'){throw 'hotspot_action_registry_not_pinned_v02'}
  $path=Join-Path $Session "intermediate/r7/producer-payloads/$PayloadName.json";Write-H6AJson $path $Payload
  $built=New-R7RuntimeSubmissionFromPayload $script:ProjectRoot $Session ([string]$prepared.Data.Task.task_envelope_id) $path $Status 1;if($built.ExitCode-ne0){throw "submission_build_failed:$($built.ResultCode):$([string]::Join(';',@($built.Errors)))"}
  $committed=Submit-R7RuntimeArtifact $script:ProjectRoot $Session ([string]$built.Data.SubmissionPath);if($committed.ExitCode-ne0){throw "submission_commit_failed:$($committed.ResultCode):$([string]::Join(';',@($committed.Errors)))"};return [pscustomobject]@{Prepared=$prepared;Built=$built;Committed=$committed}
}

try{
  $script:ProjectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$work=Resolve-H6APath $WorkRoot;$human=Resolve-H6APath $HumanReportPath;$machine=Resolve-H6APath $MachineReportPath
  foreach($path in @($work,(Split-Path -Parent $human),(Split-Path -Parent $machine))){if(-not(Test-Path $path)){New-Item -ItemType Directory -Path $path -Force|Out-Null}}
  $runRoot=Join-Path $work ('RUN-'+(Get-Date -Format 'yyyyMMdd-HHmmss')+'-'+[guid]::NewGuid().ToString('N').Substring(0,6));New-Item -ItemType Directory $runRoot|Out-Null;$session=Join-Path $runRoot 'S-R7-H6A-001';New-Item -ItemType Directory $session|Out-Null
  $results=[Collections.Generic.List[object]]::new();$schemaSuite=Read-R7JsonFile (Join-Path $script:ProjectRoot 'examples/r7-h6a-hotspot-fixtures/fixture-cases.json')

  $identity=[ordered]@{schema_id='taoge://schemas/r5/account-identity-binding/v0.1';schema_version='0.1';identity_binding_id='IDENTITY-H6A-001';binding_revision=1;binding_status='verified'}
  $snapshot=[ordered]@{schema_id='taoge://schemas/r5/account-session-snapshot/v0.2';schema_version='0.2';snapshot_id='SNAP-H6A-001';snapshot_revision=1;session_id='S-R7-H6A-001';account_slug='sample-hotspot';account_display_name='Sample Hotspot';account_snapshot_status='snapshot_ready';created_at='2026-07-15T00:00:00Z'}
  $policy=[ordered]@{schema_id='taoge://schemas/r5/radar-policy/v0.1';schema_version='0.1';radar_policy_id='RADAR-H6A-001';policy_revision=1;policy_status='active';direct_used_vehicle_priority='hard_priority';spillover_threshold=3}
  Write-H6AJson (Join-Path $session 'intermediate/account-startup/account-identity-binding.json') $identity;Write-H6AJson (Join-Path $session 'intermediate/account-startup/account-snapshot.v0.2.json') $snapshot;Write-H6AJson (Join-Path $session 'intermediate/r5/radar-policy.json') $policy

  $initialized=Initialize-R7RuntimeSession $script:ProjectRoot $session 'hotspot_to_delivery_single_v0.2';if($initialized.ExitCode-ne0){throw "initialize_failed:$($initialized.ResultCode):$([string]::Join(';',@($initialized.Errors)))"}
  $requestCommit=Invoke-R7HotspotResearchRequestCommit $script:ProjectRoot $session;if($requestCommit.ExitCode-ne0){throw "request_commit_failed:$($requestCommit.ResultCode):$([string]::Join(';',@($requestCommit.Errors)))"};$requestItem=Get-R7HotspotCurrentArtifact $session 'hotspot_research_request'
  $set=New-H6AResearchSet $requestItem;$setCommit=Invoke-H6ASemanticCommit $session $set 'research_ready_for_panel' 'research-set'
  $panelCommit=Invoke-R7TopicPanelProjection $script:ProjectRoot $session;if($panelCommit.ExitCode-ne0){throw "panel_commit_failed:$($panelCommit.ResultCode):$([string]::Join(';',@($panelCommit.Errors)))"};$panelItem=Get-R7HotspotCurrentArtifact $session 'topic_selection_panel';$setItem=Get-R7HotspotCurrentArtifact $session 'hotspot_research_set'
  $decision=[pscustomobject]@{schema_id='taoge://schemas/r7/topic-selection-decision/v0.1';schema_version='0.1.0';decision_id='DEC-H6A-001';decision_revision=1;panel_ref=$panelItem.Ref;research_set_ref=$setItem.Ref;decision_code='select_one';action_code='select_topic';selected_topic_refs=@($panelItem.Payload.ordered_topic_option_refs[0]);scope_delta=$null;manual_source_input_set_ref=$null;decided_at='2026-07-15T01:10:00Z';decision_status='committed';human_instruction_summary='Select the first current topic.'}
  $decisionCommit=Invoke-H6ASemanticCommit $session $decision 'decision_committed' 'decision';$decisionItem=Get-R7HotspotCurrentArtifact $session 'topic_selection_decision'
  $sourceCommit=Invoke-R7SelectedTopicSourceCommit $script:ProjectRoot $session;if($sourceCommit.ExitCode-ne0){throw "source_commit_failed:$($sourceCommit.ResultCode):$([string]::Join(';',@($sourceCommit.Errors)))"};$sourceItem=Get-R7HotspotCurrentArtifact $session 'selected_topic_source'
  $brief=[pscustomobject]@{schema_id='taoge://schemas/r6/content-brief/v0.4';schema_version='0.4.0';brief_id='BRIEF-H6A-001';brief_revision=1;content_source_id=[string]$sourceItem.Payload.selected_topic_source_id;content_origin='hotspot_selected_topic';account_snapshot_ref='SNAP-H6A-001';target_audience='used vehicle buyers and dealers';content_goal='Explain the verified operating change and its mechanism.';core_promise='Show what changed and what the audience should examine.';claim_ids=@('CLM-H6A-001');revision_policy='generated_content';original_draft_ref=$null;selected_topic_source_ref=$sourceItem.Ref;selected_topic_content_semantic_digest=[string]$sourceItem.Payload.content_semantic_digest;brief_status='ready';next_skill='short-video-structure-planner'}
  $briefCommit=Invoke-H6ASemanticCommit $session $brief 'brief_pass' 'brief';$briefItem=Get-R7HotspotCurrentArtifact $session 'content_brief'
  $bundle=Read-R7JsonFile (Join-Path $script:ProjectRoot 'examples/r6-script-visual-fixtures/base-direct.json');$structure=Copy-H6AObject $bundle.structure_plan;$structure.structure_plan_id='STRUCT-H6A-001';$structure.plan_mode='design_before_draft';$structure.brief_id='BRIEF-H6A-001';$structure.content_source_id=[string]$sourceItem.Payload.selected_topic_source_id;$structure.content_origin='hotspot_selected_topic';$structure.account_snapshot_ref='SNAP-H6A-001';$structure.source_draft_ref=$null;$structure.source_beat_map_ref=$null;$structure.plan_status='ready';$structure.next_skill='copywriting-draft-writer'
  $structureCommit=Invoke-H6ASemanticCommit $session $structure 'structure_ready' 'structure';$structureItem=Get-R7HotspotCurrentArtifact $session 'short_video_structure_plan'
  $draft=Copy-H6AObject $bundle.draft;$draft.schema_id='taoge://schemas/r6/draft/v0.4';$draft.schema_version='0.4.0';$draft.draft_id='DRAFT-H6A-001';$draft.draft_mode='generate_from_structure';$draft.brief_ref=$briefItem.Ref;$draft.content_source_id=[string]$sourceItem.Payload.selected_topic_source_id;$draft.content_origin='hotspot_selected_topic';$draft.account_snapshot_ref='SNAP-H6A-001';$draft.body_text='A verified operating change matters because it changes how buyers and dealers evaluate the market.';$draft.normalized_body_digest=Get-R7RuntimeTextDigest $draft.body_text;$draft.original_draft_ref=$null;$draft.original_normalized_body_digest=$null;$draft.structure_plan_ref=$structureItem.Ref;$draft.review_ref=$null;$draft.revision_decision_ref=$null;$draft.authorization_refs=@();$draft.draft_status='ready';$draft.next_skill='content-beat-mapper'
  $draftCommit=Invoke-H6ASemanticCommit $session $draft 'draft_created' 'draft';$projection=Read-R7JsonFile (Join-Path $session 'intermediate/p0/state-projection.json');$plan=Read-R7JsonFile (Join-Path $session 'intermediate/p0/session-execution-plan.json')
  Add-H6AResult $results 'R7-F34' ($projection.next_step_id-eq'STEP-S-R7-H6A-001-content_beat_map'-and$plan.plan_schema_id-eq'taoge://schemas/p0/session-execution-plan/v0.8') 'front_chain_not_closed' @()

  Add-H6AResult $results 'R7-F35' ($set.research_run_record.ranking_owner-eq'r5'-and$set.research_run_record.spillover_activation_status-eq'consumed_from_r5') 'r5_spillover_contract_missing' @()
  $empty=New-H6AResearchSet $requestItem -NoRecommendation;$emptyErrors=@(Test-R7HotspotResearchSet $empty);$emptyRef=[ordered]@{artifact_id=$empty.research_set_id;revision=1;sha256='sha256:'+('a'*64)};$emptyPanel=[pscustomobject]@{schema_id='taoge://schemas/r7/topic-selection-panel/v0.2';schema_version='0.2.0';panel_id='PANEL-EMPTY';panel_revision=1;research_set_ref=$emptyRef;ordered_topic_option_refs=@();recommended_topic_ref=$null;recommendation_reason=$empty.panel_model.recommendation_reason;panel_status='panel_no_recommendation';projected_at=$empty.researched_at};$emptyPanelErrors=@(Test-R7HotspotPanel $emptyPanel $empty $emptyRef);Add-H6AResult $results 'R7-F36' ($emptyErrors.Count-eq0-and$emptyPanelErrors.Count-eq0) 'no_recommendation_contract_failed' @($emptyErrors+$emptyPanelErrors)
  $rerun=Copy-H6AObject $requestItem.Payload;$rerun.research_request_id='HRQ-H6A-RERUN';$rerun.supersedes_request_ref=$requestItem.Ref;$rerun.triggering_decision_ref=$decisionCommit.Committed.Data;$rerun.prior_research_set_ref=$setItem.Ref;$rerun.prior_panel_ref=$panelItem.Ref;$rerun.request_mode='same_policy_rerun';$rerunErrors=@(Test-R7HotspotResearchRequest $rerun);Add-H6AResult $results 'R7-F37' ($rerunErrors.Count-eq0-and$rerun.research_request_id-ne$requestItem.Payload.research_request_id) 'rerun_identity_failed' $rerunErrors
  $beforeDigest=Get-R7HotspotCanonicalDigest $set.topic_options[0];$decisionErrors=@(Test-R7HotspotDecision $decision $panelItem.Payload $set);$afterDigest=Get-R7HotspotCanonicalDigest $set.topic_options[0];Add-H6AResult $results 'R7-F38' ($decisionErrors.Count-eq0-and$beforeDigest-eq$afterDigest) 'decision_mutated_topic' $decisionErrors
  $briefErrors=@(Test-R7HotspotBriefV04 $brief $sourceItem.Ref $sourceItem.Payload);Add-H6AResult $results 'R7-F39' ($briefErrors.Count-eq0) 'brief_source_union_failed' $briefErrors
  $future=Copy-H6AObject $structure;$future.source_draft_ref=[ordered]@{artifact_id='FUTURE';revision=1;sha256='sha256:'+('b'*64)};$futureErrors=@(Test-R7HotspotStructurePlan $future ([ordered]@{artifact_id=$brief.brief_id}) ([ordered]@{artifact_id=$sourceItem.Payload.selected_topic_source_id}));Add-H6AResult $results 'R7-F40' (@($futureErrors|Where-Object{$_-like'future_artifact_reference*'}).Count-gt0) 'future_reference_not_blocked' $futureErrors
  $order=@((Get-R7RuntimeBlueprint (Get-R7RuntimeRegistries $script:ProjectRoot) 'hotspot_to_delivery_single_v0.2').node_refs);$draftIndex=[array]::IndexOf($order,'hotspot_draft');$beatIndex=[array]::IndexOf($order,'content_beat_map');Add-H6AResult $results 'R7-F41' ($draftIndex-ge0-and$beatIndex-eq($draftIndex+1)) 'shared_chain_order_invalid' @()
  $high=New-H6AResearchSet $requestItem -HighRisk;$highErrors=@(Test-R7HotspotResearchSet $high);Add-H6AResult $results 'R7-F45' ($highErrors.Count-eq0-and$high.topic_evidence_packets[0].claims[0].allowed_expression-eq'attribute_to_source') 'high_risk_attribution_failed' $highErrors
  $multi=Copy-H6AObject $decision;$multi.decision_code='select_multiple';$multi.action_code='branch_selected_topics';$second=Copy-H6AObject $multi.selected_topic_refs[0];$second.component_id='TOPIC-H6A-002';$second.component_sha256='sha256:'+('c'*64);$multi.selected_topic_refs=@($multi.selected_topic_refs[0],$second);Add-H6AResult $results 'R7-F48' ($multi.action_code-eq'branch_selected_topics') 'multi_route_invalid' @()
  $mismatch=Copy-H6AObject $set;$mismatch.account_identity_ref.artifact_id='IDENTITY-OTHER';$bindingErrors=@(Test-R7HotspotResearchSetBinding $mismatch $requestItem.Payload $requestItem.Ref);Add-H6AResult $results 'R7-F49' (@($bindingErrors|Where-Object{$_-like'account_identity_inconsistent*'}).Count-gt0) 'account_mismatch_not_blocked' $bindingErrors
  $researchNode=Get-R7RuntimeNode (Get-R7RuntimeRegistries $script:ProjectRoot) 'hotspot_research';Add-H6AResult $results 'R7-F52' ($researchNode.output_artifact_type-eq'hotspot_research_set') 'multiple_research_outputs_allowed' @()
  $badSet=Copy-H6AObject $set;$badSet.panel_model.ordered_topic_option_refs[0].component_sha256='sha256:'+('d'*64);$badSetErrors=@(Test-R7HotspotResearchSet $badSet);Add-H6AResult $results 'R7-F53' (@($badSetErrors|Where-Object{$_-like'*digest_map_mismatch*'}).Count-gt0) 'component_digest_mismatch_not_blocked' $badSetErrors
  $badSelect=Copy-H6AObject $decision;$badSelect.selected_topic_refs=@();$badSelectErrors=@(Test-R7HotspotDecision $badSelect $panelItem.Payload $set);Add-H6AResult $results 'R7-F54' (@($badSelectErrors|Where-Object{$_-like'*select_one_condition_mismatch*'}).Count-gt0) 'select_cardinality_not_blocked' $badSelectErrors
  $emptySelect=Copy-H6AObject $decision;$emptySelect.panel_ref=[ordered]@{artifact_id='PANEL-EMPTY';revision=1;sha256='sha256:'+('e'*64)};$emptySelect.research_set_ref=$emptyRef;$emptySelect.selected_topic_refs=@([ordered]@{container_artifact_ref=$emptyRef;component_type='topic_option';component_id='TOPIC-NONE';component_sha256='sha256:'+('f'*64)});$emptySelectErrors=@(Test-R7HotspotDecision $emptySelect $emptyPanel $empty);Add-H6AResult $results 'R7-F55' (@($emptySelectErrors|Where-Object{$_-like'*selection_forbidden*'}).Count-gt0) 'no_recommendation_selection_not_blocked' $emptySelectErrors
  $broad=Copy-H6AObject $decision;$broad.decision_code='broaden_within_account_policy';$broad.action_code='broaden_hotspot_scope';$broad.selected_topic_refs=@();$broad.scope_delta=[pscustomobject]@{};$broadErrors=@(Test-R7HotspotDecision $broad $panelItem.Payload $set);Add-H6AResult $results 'R7-F56' (@($broadErrors|Where-Object{$_-like'*broaden_condition_mismatch*'}).Count-gt0) 'empty_scope_not_blocked' $broadErrors
  $manual=Copy-H6AObject $decision;$manual.decision_code='add_manual_source';$manual.action_code='attach_manual_hotspot_source';$manual.selected_topic_refs=@();$manual|Add-Member -NotePropertyName source_url -NotePropertyValue 'https://example.invalid/raw';$manualErrors=@(Test-R7HotspotDecision $manual $panelItem.Payload $set);Add-H6AResult $results 'R7-F57' (@($manualErrors|Where-Object{$_-like'*unknown_field:source_url*'-or$_-like'*manual_condition_mismatch*'}).Count-gt0) 'raw_url_not_blocked' $manualErrors
  $mutatedPanel=Copy-H6AObject $panelItem.Payload;$mutatedPanel.ordered_topic_option_refs=@();$mutatedErrors=@(Test-R7HotspotPanel $mutatedPanel $set $setItem.Ref);Add-H6AResult $results 'R7-F58' (@($mutatedErrors|Where-Object{$_-like'*ranking_changed*'}).Count-gt0) 'panel_mutation_not_blocked' $mutatedErrors
  $legacyBrief=Copy-H6AObject $brief;$legacyBrief.content_origin='hotspot_topic';$legacyBrief.next_skill='copywriting-draft-writer';$legacyBriefErrors=@(Test-R7HotspotBriefV04 $legacyBrief $sourceItem.Ref $sourceItem.Payload);Add-H6AResult $results 'R7-F59' ($legacyBriefErrors.Count-gt0) 'legacy_brief_not_blocked' $legacyBriefErrors
  $missingStructure=Copy-H6AObject $draft;$missingStructure.structure_plan_ref=$null;$missingStructureErrors=@(Test-R7HotspotDraftV04 $missingStructure $briefItem.Ref $structureItem.Ref);Add-H6AResult $results 'R7-F60' ($missingStructureErrors.Count-gt0) 'missing_structure_not_blocked' $missingStructureErrors
  $wrongPlan=Copy-H6AObject $plan;$wrongPlan.plan_schema_id='taoge://schemas/p0/session-execution-plan/v0.7';$wrongPlan.contract_bundle_version='p0-contract-bundle-v0.7';$wrongPlan.workflow_definition_version='r7-single-semantic-workflow-v0.2';$wrongPlan.render_input_schema_id='taoge://schemas/final-delivery/typed-components/v0.6';$wrongPlan.renderer_version='final-delivery-renderer-v0.6';$wrongPlan.template_version='final-delivery-template-v0.6';$wrongPlanErrors=@(Test-P0PlanContract $wrongPlan);$compat=Read-R7JsonFile (Join-Path $script:ProjectRoot 'templates/schema/r7/compatibility-matrix.v0.2.json');$directCompat=@($compat.entries|Where-Object{$_.workflow_contract-eq'direct_delivery_single_v0.2'})|Select-Object -First 1;$hotspotCompat=@($compat.entries|Where-Object{$_.workflow_contract-eq'hotspot_to_delivery_single_v0.2'})|Select-Object -First 1;Add-H6AResult $results 'R7-F61' ($wrongPlanErrors.Count-gt0-and$directCompat.plan_contract-eq'p0-session-execution-plan-v0.7'-and$directCompat.delivery_contract-eq'p0-delivery-v0.6'-and$hotspotCompat.plan_contract-eq'p0-session-execution-plan-v0.8'-and$hotspotCompat.new_session_status-eq'fixture_only_h6b_delivery_pending') 'version_compatibility_boundary_failed' $wrongPlanErrors
  $unsafe=Copy-H6AObject $high.topic_evidence_packets[0];$unsafe.claims[0].allowed_expression='assert_as_fact';$unsafeErrors=@(Test-R7HotspotEvidencePacket $unsafe);Add-H6AResult $results 'R7-F67' ($unsafeErrors.Count-gt0) 'high_risk_assertion_not_blocked' $unsafeErrors
  $missingRequestSession=Join-Path $runRoot 'S-R7-H6A-MISSING';New-Item -ItemType Directory $missingRequestSession|Out-Null;$missingSelector=@((Get-R7RuntimeRegistries $script:ProjectRoot).Selectors.selectors|Where-Object{$_.selector_id-eq'current_hotspot_research_request'})|Select-Object -First 1;$missingBlocked=$false;try{$null=Resolve-R7RuntimeBinding $script:ProjectRoot $missingRequestSession $missingSelector}catch{$missingBlocked=$_.Exception.Message-like'selector_input_missing:current_hotspot_research_request*'};Add-H6AResult $results 'R7-F70' $missingBlocked 'missing_request_not_blocked' @()
  $badRerun=Copy-H6AObject $rerun;$badRerun.scope_delta=[ordered]@{extra='forbidden'};$badRerunErrors=@(Test-R7HotspotResearchRequest $badRerun);Add-H6AResult $results 'R7-F71' ($badRerunErrors.Count-gt0) 'request_condition_mismatch_not_blocked' $badRerunErrors
  Add-H6AResult $results 'R7-F72' ($multi.action_code-eq'branch_selected_topics'-and$researchNode.output_artifact_type-ne'branch_request') 'h6_multi_handoff_leak' @()
  Add-H6AResult $results 'R7-F73' (@($mutatedErrors|Where-Object{$_-like'*ranking_changed*'}).Count-gt0) 'projector_rerank_not_blocked' $mutatedErrors
  $deliverySource=Copy-H6AObject $sourceItem.Payload;$deliverySource.selected_source_status='ready_for_delivery';$deliveryBriefErrors=@(Test-R7HotspotBriefV04 $brief $sourceItem.Ref $deliverySource);Add-H6AResult $results 'R7-F74' (@($deliveryBriefErrors|Where-Object{$_-like'*source_status_invalid*'}).Count-gt0) 'consumer_status_not_blocked' $deliveryBriefErrors
  $badPolicy=Copy-H6AObject $sourceItem.Payload.freshness_policy;$badPolicy.policy_mode='duration_bound';$badPolicy.max_age_hours=24;$badPolicy.fallback_reason=$null;$policyErrors=@(Test-R7HotspotFreshnessPolicy $badPolicy);Add-H6AResult $results 'R7-F75' ($policyErrors.Count-gt0) 'basisless_duration_not_blocked' $policyErrors
  $digestA=Get-R7HotspotCanonicalDigest ([ordered]@{b=2;a=1});$digestB=Get-R7HotspotCanonicalDigest ([ordered]@{a=1;b=2});$semanticBefore=Get-R7HotspotCanonicalDigest $set.topic_evidence_packets[0];$changedPacket=Copy-H6AObject $set.topic_evidence_packets[0];$changedPacket.claims[0].allowed_expression='state_uncertainty';$semanticAfter=Get-R7HotspotCanonicalDigest $changedPacket;Add-H6AResult $results 'R7-F76' ($digestA-eq$digestB-and$semanticBefore-ne$semanticAfter) 'canonical_digest_contract_failed' @()
  $singleSecondary=Copy-H6AObject $set.topic_evidence_packets[0];$singleSecondary.claims[0].source_support_basis='single_eligible_secondary';$singleSecondary.claims[0].allowed_expression='assert_as_fact';$secondaryErrors=@(Test-R7HotspotEvidencePacket $singleSecondary);Add-H6AResult $results 'R7-F77' ($secondaryErrors.Count-gt0) 'single_secondary_assertion_not_blocked' $secondaryErrors
  $decision2=Copy-H6AObject $decision;$decision2.decision_id='DEC-H6A-002';$sourceId1='STS-S-R7-H6A-001-'+(Get-R7HotspotCanonicalDigest $decisionItem.Ref).Substring(7,12);$decision2Ref=[ordered]@{artifact_id=$decision2.decision_id;revision=1;sha256=Get-R7HotspotCanonicalDigest $decision2};$sourceId2='STS-S-R7-H6A-001-'+(Get-R7HotspotCanonicalDigest $decision2Ref).Substring(7,12);Add-H6AResult $results 'R7-F80' ($sourceId1-ne$sourceId2) 'new_selection_reused_source_id' @()

  $known=@($schemaSuite.cases|ForEach-Object{[string]$_.fixture_id});foreach($result in @($results)){if([string]$result.fixture_id-notin$known){$result.expectation_met=$false;$result.actual_result='fixture_not_registered'}}
  $mismatches=@($results|Where-Object{-not$_.expectation_met});$report=[ordered]@{r7_h6a_hotspot_report=[ordered]@{check_run_id='R7-H6A-'+(Get-Date -Format 'yyyyMMdd-HHmmss');overall_result=$(if($mismatches.Count){'fail'}else{'pass'});exit_code=$(if($mismatches.Count){1}else{0});fixture_count=$results.Count;mismatch_count=$mismatches.Count;runtime_front_chain_next_node=[string]$projection.next_step_id;not_tested_scope=@('freshness_apply','typed_delivery_v0.7','renderer_v0.7','real_network_research','source_capture','image_provider','account_login','publishing','l3_real_evidence');checks=[object[]]$results.ToArray()}}
  Write-TaogeUtf8NoBomJson $machine $report 80;$lines=@('# R7-H6A Hotspot Front-Chain Check','',"overall_result: $($report.r7_h6a_hotspot_report.overall_result)","fixture_count: $($results.Count)","runtime_front_chain_next_node: $($projection.next_step_id)",'','| Fixture | Actual | Matched | Errors |','|---|---|---:|---|');foreach($item in $results){$lines+="| $($item.fixture_id) | $($item.actual_result) | $($item.expectation_met) | $([string]::Join(';',@($item.errors))) |"};Write-TaogeUtf8NoBomLines $human $lines
  if($mismatches.Count){Write-Output 'R7_H6A_HOTSPOT_RESULT=fail';foreach($item in $mismatches){Write-Output "R7_H6A_ERROR=$($item.fixture_id):$($item.actual_result):$([string]::Join(';',@($item.errors)))"};exit 1};Write-Output 'R7_H6A_HOTSPOT_RESULT=pass';Write-Output "R7_H6A_FIXTURE_COUNT=$($results.Count)";Write-Output "R7_H6A_NEXT_NODE=$($projection.next_step_id)";exit 0
}catch{Write-Error("{0} at line {1}: {2}"-f$_.Exception.Message,$_.InvocationInfo.ScriptLineNumber,$_.InvocationInfo.Line);exit 3}
