param(
  [string]$ProjectRoot=(Split-Path -Parent $PSScriptRoot),
  [string]$WorkRoot='',
  [string]$ReportPath=''
)
$ErrorActionPreference='Stop'
$ProjectRoot=[IO.Path]::GetFullPath($ProjectRoot)
if([string]::IsNullOrWhiteSpace($WorkRoot)){$WorkRoot=Join-Path $ProjectRoot 'state/checks/r7-l3-h3-direct-route-work'}
if([string]::IsNullOrWhiteSpace($ReportPath)){$ReportPath=Join-Path $ProjectRoot 'state/checks/r7-l3-h3-direct-route-report.json'}
$WorkRoot=[IO.Path]::GetFullPath($WorkRoot);if(-not$WorkRoot.StartsWith($ProjectRoot.TrimEnd('\')+'\',[StringComparison]::OrdinalIgnoreCase)){throw 'work_root_outside_project'}
if(Test-Path -LiteralPath $WorkRoot){Remove-Item -LiteralPath $WorkRoot -Recurse -Force};New-Item -ItemType Directory -Path $WorkRoot -Force|Out-Null
. (Join-Path $ProjectRoot 'tools/R7SemanticRuntime.ps1')
. (Join-Path $ProjectRoot 'tools/R7VisualSemanticRuntime.ps1')
. (Join-Path $ProjectRoot 'tools/R7HumanRevisionRuntime.ps1')
. (Join-Path $ProjectRoot 'tools/R7H7DeliveryContract.ps1')
$results=[Collections.Generic.List[object]]::new();function Add-Result([string]$Id,[bool]$Pass,[object[]]$Evidence){$results.Add([pscustomobject]@{case_id=$Id;status=$(if($Pass){'pass'}else{'fail'});evidence=[object[]]$Evidence})}
function Write-Current([string]$Session,[string]$Type,[string]$Id,[object]$Payload){$relative="intermediate/r7/revisions/$Type/$Id.json";$path=Resolve-R7RuntimePath $Session $relative;Write-P0EvidenceAtomicText $path (ConvertTo-P0EvidenceJsonText $Payload);$pointer=[ordered]@{schema_id='taoge://schemas/r7/semantic-current-pointer/v0.1';schema_version='0.1';artifact_type=$Type;artifact_id=$Id;revision=1;revision_path=$relative;sha256=Get-R7RuntimeHash $path;status='complete';task_envelope_id='FIXTURE-SEED';submission_id='FIXTURE-SEED';producer_event_id='FIXTURE-SEED';committed_at='2026-07-16T00:00:00+08:00'};Write-P0EvidenceAtomicText (Resolve-R7RuntimePath $Session "intermediate/r7/current/$Type.json") (ConvertTo-P0EvidenceJsonText $pointer)}

$registries=Get-R7RuntimeRegistries $ProjectRoot;$plan=New-R7RuntimePlan 'R7-L3-H3-REDACTED' 'direct_delivery_single_v0.5' $registries 'no_provider';$planErrors=@(Test-P0PlanContract $plan);$order=@($plan.steps|Where-Object{$_.node_id-ne'session_plan'}|ForEach-Object{[string]$_.node_id});$expected=@('visual_need_analysis','visual_intent_decision_set','visual_source_route_decision_set','visual_prompt_brief_set','visual_production_l3','visual_asset_review_set','visual_asset_finalize_l3');$actual=@($order[([Array]::IndexOf([string[]]$order,'visual_need_analysis'))..([Array]::IndexOf([string[]]$order,'visual_asset_finalize_l3'))]);Add-Result 'H3-001-current-direct-v05-plan' ($planErrors.Count-eq0-and[string]::Join('|',$actual)-eq[string]::Join('|',$expected)) @($planErrors+$actual)
$old=@($registries.Blueprints.blueprints|Where-Object{$_.blueprint_id-eq'direct_delivery_single_v0.4'})|Select-Object -First 1;Add-Result 'H3-002-v04-replay-only' ([string]$old.activation_status-eq'historical_replay_only_superseded_by_direct_v05') @([string]$old.activation_status)
$newNodes=@('visual_intent_decision_set','visual_source_route_decision_set','visual_prompt_brief_set','visual_production_l3','visual_asset_review_set','visual_asset_finalize_l3','delivery_visual_review','business_delivery_acceptance_l3');$registryErrors=[Collections.Generic.List[string]]::new();foreach($nodeId in $newNodes){$node=@($registries.Nodes.nodes|Where-Object{$_.node_id-eq$nodeId});$route=@($registries.StatusRoutes.nodes|Where-Object{$_.node_id-eq$nodeId});if($node.Count-ne1-or$route.Count-ne1){$registryErrors.Add("registry_count:$nodeId");continue};$all=@(@($route[0].success)+@($route[0].warning)+@($route[0].waiting)+@($route[0].failure)|Sort-Object);if([string]::Join('|',@($node[0].allowed_result_statuses|Sort-Object))-ne[string]::Join('|',$all)){$registryErrors.Add("status_parity:$nodeId")}};Add-Result 'H3-003-registry-status-parity' ($registryErrors.Count-eq0) @($registryErrors)

$digest='sha256:'+('1'*64);$now='2026-07-16T00:00:00+08:00';$intentRecord=[pscustomobject]@{schema_id='taoge://schemas/r3/visual-intent-decision/v0.1';schema_version='0.1';decision_id='VID-NO-VISUAL';decision_revision=1;session_id='REDACTED';visual_task_id='VT-001';beat_ref=[pscustomobject]@{artifact_id='BEAT-001'};role='visual_director';account_snapshot_ref=[pscustomobject]@{artifact_id='SNAP-001'};viewer_problem='none';value_jobs=@();counterfactual_loss='The spoken beat remains concrete without an insert.';decision='no_visual';no_visual_reason='The presenter already demonstrates the concrete point and an insert would duplicate it.';evidence_requirement_ref=$null;producer_task_envelope_ref=[pscustomobject]@{task_envelope_id='TASK-INTENT'};input_binding_digest=$digest;decided_at=$now;next_stage='complete_no_visual'}
$routeRecord=[pscustomobject]@{schema_id='taoge://schemas/r3/visual-source-route-decision/v0.1';schema_version='0.1';route_decision_id='VRD-NO-VISUAL';route_revision=1;session_id='REDACTED';visual_task_id='VT-001';intent_ref=[pscustomobject]@{artifact_id='VID-NO-VISUAL'};role='visual_director';source_class=$null;classification_basis='Intent explicitly concluded no visual.';claim_ref=$null;evidence_requirement_ref=$null;asset_reuse_authorization_ref=$null;account_snapshot_ref=[pscustomobject]@{artifact_id='SNAP-001'};excluded_source_class_reasons=@();production_path='not_applicable';test_profile='no_provider';route_status='not_applicable_no_visual';producer_task_envelope_ref=[pscustomobject]@{task_envelope_id='TASK-ROUTE'};input_binding_digest=$digest;decided_at=$now;next_stage='complete_no_visual'}
function New-StageSet([string]$Id,[string]$Stage,[object[]]$Records,[string]$Status,[string]$Next){[pscustomobject]@{schema_id='taoge://schemas/r3/visual-stage-set/v0.1';schema_version='0.1';stage_set_id=$Id;set_revision=1;session_id='REDACTED';stage=$Stage;source_coverage_ref=[pscustomobject]@{artifact_id='LEDGER-001';sha256=$digest};records=[object[]]$Records;record_count=$Records.Count;set_status=$Status;producer_task_envelope_ref=[pscustomobject]@{task_envelope_id="TASK-$Id"};input_binding_digest=$digest;created_at=$now;next_stage=$Next}}
$intentSet=New-StageSet 'VIS-INTENT-001' 'visual_intent_decision' @($intentRecord) 'complete_no_visual' 'visual_source_route_decision_set';$routeSet=New-StageSet 'VIS-ROUTE-001' 'visual_source_route_decision' @($routeRecord) 'complete_no_visual' 'visual_prompt_brief_set';$promptSet=New-StageSet 'VIS-PROMPT-001' 'visual_prompt_brief' @() 'complete_no_visual' 'visual_production_l3';$reviewSet=New-StageSet 'VIS-REVIEW-001' 'visual_asset_review' @() 'complete_no_visual' 'visual_asset_finalize_l3';$stageErrors=@(Test-R7VisualStageSet $intentSet 'visual_intent_decision')+@(Test-R7VisualStageSet $routeSet 'visual_source_route_decision')+@(Test-R7VisualStageSet $promptSet 'visual_prompt_brief')+@(Test-R7VisualStageSet $reviewSet 'visual_asset_review')
$emptyAssets=[pscustomobject]@{schema_id='taoge://schemas/r7/image-asset-set/v0.4';schema_version='0.4';image_asset_set_id='ASSETSET-EMPTY';coverage_ledger_ref=[pscustomobject]@{artifact_id='LEDGER-001'};visual_route_set_ref=[pscustomobject]@{artifact_id='VIS-ROUTE-001'};visual_prompt_set_ref=[pscustomobject]@{artifact_id='VIS-PROMPT-001'};test_profile='no_provider';finalize_requested_at=$now;assets=@();delivery_bindings=@();provider_task_count=0;provider_attempt_count=0;provider_invocation_count=0;source_capture_attempt_count=0;postprocess_count=0;asset_set_status='no_visual_waiting_review';next_skill='visual-asset-reviewer'};$emptyFinalize=New-R7L3ImageAssetDeliverySet $WorkRoot $emptyAssets $digest $reviewSet $digest;Add-Result 'H3-004-zero-visual-typed-closure' ($stageErrors.Count-eq0-and$emptyFinalize.ExitCode-eq0-and$emptyFinalize.Data.finalize_status-eq'finalized_no_visual'-and[int]$emptyFinalize.Data.delivery_asset_count-eq0) @($stageErrors+[string]$emptyFinalize.ResultCode)

$session=Join-Path $WorkRoot 'R7-L3-H3-SESSION';New-Item -ItemType Directory -Path $session -Force|Out-Null;$init=Initialize-R7RuntimeSession $ProjectRoot $session 'direct_delivery_single_v0.5' 'no_provider';$accountPath=Resolve-R7RuntimePath $session 'intermediate/account-startup/account-snapshot.v0.2.json';Write-P0EvidenceAtomicText $accountPath (ConvertTo-P0EvidenceJsonText ([pscustomobject]@{snapshot_id='SNAP-REDACTED';account_snapshot_status='ready'}));Write-Current $session 'content_beat_map' 'BEATMAP-REDACTED' ([pscustomobject]@{beat_map_id='BEATMAP-REDACTED';mapping_status='ready'});Write-Current $session 'visual_coverage_ledger' 'LEDGER-REDACTED' ([pscustomobject]@{visual_coverage_ledger_id='LEDGER-REDACTED';coverage_completeness_status='complete'})
$eventPath=Join-Path $session 'intermediate/p0/execution-events.jsonl';$runtimePlan=Read-P0JsonFile (Join-Path $session 'intermediate/p0/session-execution-plan.json');$pre=@($runtimePlan.steps|Where-Object{$_.node_id-ne'session_plan'});foreach($step in $pre){$events=@(Get-P0EvidenceEvents $eventPath);$source=switch([string]$step.step_kind){'agent_required'{'agent_recorder'}'human_gate'{'human_recorder'}'external_side_effect'{'reconciler'}default{'runner'}};$before=switch([string]$step.step_kind){'human_gate'{'waiting_human'}'external_side_effect'{'waiting_external'}default{'waiting_agent'}};$seed=Write-P0EvidenceEvent -EventPath $eventPath -Plan $runtimePlan -StepId ([string]$step.step_id) -EventType 'fixture.prerequisite.v1' -EventSource $source -StateBefore $before -StateAfter 'succeeded' -PayloadDigest $digest -IdempotencyKey "fixture:$($step.step_id)" -ExpectedLastSequenceNo $events.Count -ResultCode 'fixture_prerequisite' -SafeSummary 'Redacted prerequisite fixture' -OutputArtifactIds @("FIX-$($step.node_id)") -InputDigest $digest -ExecutionAttemptId "ATT-$($step.node_id)";if($seed.ExitCode-ne0){throw "fixture_seed_event_failed:$($seed.ResultCode)"};if($step.node_id-eq'visual_need_analysis'){break}}
[void](Update-P0StateProjection $session $runtimePlan $eventPath $false);$taskIntent=Prepare-R7RuntimeTask $ProjectRoot $session;$task=$taskIntent.Data.Task;$runtimeIntent=[pscustomobject](($intentRecord|ConvertTo-Json -Depth 30)|ConvertFrom-Json);$runtimeIntent.decision='required';$runtimeIntent.viewer_problem='comprehension_gap';$runtimeIntent.value_jobs=@('understanding');$runtimeIntent.no_visual_reason='';$runtimeIntent.next_stage='visual_source_route_decision';$runtimeIntent.session_id='R7-L3-H3-SESSION';$runtimeIntent.producer_task_envelope_ref=[pscustomobject]@{task_envelope_id=[string]$task.task_envelope_id};$runtimeIntent.input_binding_digest='sha256:'+[string]$task.input_binding_digest;$runtimeIntentSet=New-StageSet 'VIS-INTENT-RUNTIME' 'visual_intent_decision' @($runtimeIntent) 'complete' 'visual_source_route_decision_set';$runtimeIntentSet.session_id='R7-L3-H3-SESSION';$runtimeIntentSet.producer_task_envelope_ref=[pscustomobject]@{task_envelope_id=[string]$task.task_envelope_id};$runtimeIntentSet.input_binding_digest='sha256:'+[string]$task.input_binding_digest;$payloadPath=Join-Path $session 'intermediate/r7/fixture-intent.json';Write-P0EvidenceAtomicText $payloadPath (ConvertTo-P0EvidenceJsonText $runtimeIntentSet);$built=New-R7RuntimeSubmissionFromPayload $ProjectRoot $session ([string]$task.task_envelope_id) $payloadPath 'complete';$submitted=Submit-R7RuntimeArtifact $ProjectRoot $session ([string]$built.Data.SubmissionPath);$routeTaskResult=Prepare-R7RuntimeTask $ProjectRoot $session;$routeTask=$routeTaskResult.Data.Task
$waitingRoute=[pscustomobject]@{schema_id='taoge://schemas/r3/visual-source-route-decision/v0.1';schema_version='0.1';route_decision_id='VRD-WAIT';route_revision=1;session_id='R7-L3-H3-SESSION';visual_task_id='VT-001';intent_ref=[pscustomobject]@{artifact_id='VID-NO-VISUAL'};role='visual_director';source_class='generated_context';classification_basis='The abstract mechanism needs a generated explanatory scene.';claim_ref=$null;evidence_requirement_ref=$null;asset_reuse_authorization_ref=$null;account_snapshot_ref=[pscustomobject]@{artifact_id='SNAP-REDACTED'};excluded_source_class_reasons=@();production_path='codex_builtin_image2';test_profile='no_provider';route_status='waiting_capability';producer_task_envelope_ref=[pscustomobject]@{task_envelope_id=[string]$routeTask.task_envelope_id};input_binding_digest='sha256:'+[string]$routeTask.input_binding_digest;decided_at=$now;next_stage='waiting_capability'};$waitingSet=New-StageSet 'VIS-ROUTE-WAIT' 'visual_source_route_decision' @($waitingRoute) 'waiting_capability' 'waiting_capability';$waitingSet.session_id='R7-L3-H3-SESSION';$waitingSet.producer_task_envelope_ref=[pscustomobject]@{task_envelope_id=[string]$routeTask.task_envelope_id};$waitingSet.input_binding_digest='sha256:'+[string]$routeTask.input_binding_digest;$waitPath=Join-Path $session 'intermediate/r7/fixture-route-wait.json';Write-P0EvidenceAtomicText $waitPath (ConvertTo-P0EvidenceJsonText $waitingSet);$waitBuilt=New-R7RuntimeSubmissionFromPayload $ProjectRoot $session ([string]$routeTask.task_envelope_id) $waitPath 'waiting_capability';$waitSubmit=Submit-R7RuntimeArtifact $ProjectRoot $session ([string]$waitBuilt.Data.SubmissionPath);$resume=Prepare-R7RuntimeTask $ProjectRoot $session;$routePointer=Join-Path $session 'intermediate/r7/current/visual_source_route_decision_set.json';Add-Result 'H3-005-honest-wait-resume' ($init.ExitCode-eq0-and$submitted.ExitCode-eq0-and$waitSubmit.ResultCode-eq'semantic_waiting'-and$waitSubmit.ExitCode-eq2-and-not(Test-Path -LiteralPath $routePointer)-and[string]$resume.Data.Task.task_envelope_id-eq[string]$routeTask.task_envelope_id) @([string]$init.ResultCode,[string]$submitted.ResultCode,[string]$waitSubmit.ResultCode,[string]$resume.ResultCode)

$request=[pscustomobject]@{revision_request_id='DREQ-REDACTED-002';request_digest=$digest;restart_from_node_id='visual_source_route_decision_set';carried_forward_artifact_refs=@([pscustomobject]@{artifact_id='VIS-INTENT-RUNTIME';sha256=$digest});invalidated_artifact_refs=@([pscustomobject]@{artifact_id='VIS-ROUTE-WAIT';sha256=$digest})};$replan=New-R7HumanRevisionPlan $plan $request;$replanErrors=@(Test-P0PlanContract $replan);$branch=@($replan.steps|Where-Object{$_.step_id-match'-R2$'});Add-Result 'H3-006-scoped-revision-plan' ($replanErrors.Count-eq0-and$replan.plan_revision-eq2-and$branch.Count-gt0-and[string]$branch[0].node_id-eq'visual_source_route_decision_set'-and[string]$branch[-1].node_id-eq'final_human_gate_h7') @($replanErrors+@($branch|ForEach-Object{[string]$_.node_id}))
$fixture=Get-Content -LiteralPath (Join-Path $ProjectRoot 'examples/r7-l3-h3-direct-route-fixture/cases.json') -Raw -Encoding UTF8|ConvertFrom-Json;Add-Result 'H3-007-redacted-fixture-manifest' ([string]$fixture.privacy_class-eq'public_redacted_synthetic'-and@($fixture.cases).Count-eq5) @([string]$fixture.privacy_class)
$report=[pscustomobject]@{schema_id='taoge://reports/r7/l3-h3-direct-route/v0.1';schema_version='0.1';generated_at=[DateTimeOffset]::UtcNow.ToString('o');fixture_privacy='public_redacted_synthetic';case_count=$results.Count;passed_count=@($results|Where-Object{$_.status-eq'pass'}).Count;failed_count=@($results|Where-Object{$_.status-eq'fail'}).Count;project_maturity='L2.8';real_provider_invocations=0;real_network_calls=0;results=[object[]]$results.ToArray()};Write-P0EvidenceAtomicText $ReportPath (ConvertTo-P0EvidenceJsonText $report);$report|ConvertTo-Json -Depth 20;if($report.failed_count){exit 1}
