param([string]$ProjectRoot=(Split-Path -Parent $PSScriptRoot))
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'P0RuntimeV02.ps1')
. (Join-Path $PSScriptRoot 'R7ContractHelper.ps1')
. (Join-Path $PSScriptRoot 'R7SemanticRuntime.ps1')
. (Join-Path $PSScriptRoot 'R7H7DeliveryContract.ps1')

$work=Join-Path $ProjectRoot 'state/checks/r7-h7-fixture-work'
if(Test-Path -LiteralPath $work){Remove-Item -LiteralPath $work -Recurse -Force}
[void](New-Item -ItemType Directory -Path (Join-Path $work 'assets') -Force)
[void](New-Item -ItemType Directory -Path (Join-Path $work 'reviews') -Force)
[void](New-Item -ItemType Directory -Path (Join-Path $work 'records') -Force)
Write-P0EvidenceAtomicText (Join-Path $work 'assets/base.png') 'base-fixture'
Write-P0EvidenceAtomicText (Join-Path $work 'assets/final.png') 'final-fixture'
Write-P0EvidenceAtomicText (Join-Path $work 'records/base.sidecar.json') '{"kind":"sidecar"}'
Write-P0EvidenceAtomicText (Join-Path $work 'records/base.generation.json') '{"kind":"generation","provider_attempt_refs":["ATT-1"]}'
Write-P0EvidenceAtomicText (Join-Path $work 'records/final.sidecar.json') '{"kind":"sidecar"}'
Write-P0EvidenceAtomicText (Join-Path $work 'records/final.layout.json') '{"kind":"postprocess","step":"deterministic_overlay"}'
$baseHash=Get-R7RuntimeHash (Join-Path $work 'assets/base.png');$finalHash=Get-R7RuntimeHash (Join-Path $work 'assets/final.png')
$baseSidecarHash=Get-R7RuntimeHash (Join-Path $work 'records/base.sidecar.json');$generationHash=Get-R7RuntimeHash (Join-Path $work 'records/base.generation.json');$finalSidecarHash=Get-R7RuntimeHash (Join-Path $work 'records/final.sidecar.json');$postHash=Get-R7RuntimeHash (Join-Path $work 'records/final.layout.json')
$review=[ordered]@{schema_id='taoge://schemas/r3/visual-asset-review/v0.1';visual_review_status='pass';output_sha256=$finalHash;checks=@('text_accuracy','crop','readability','semantic_fit','safe_area')}
Write-P0EvidenceAtomicText (Join-Path $work 'reviews/final.json') (ConvertTo-P0EvidenceJsonText $review)
$reviewHash=Get-R7RuntimeHash (Join-Path $work 'reviews/final.json')
$baseAsset=[ordered]@{asset_id='A-BASE';asset_revision=1;visual_task_id='VT-1';asset_role='base';source_class='generated_context';route_decision='image2_generated_context';parent_asset_ref=$null;relative_path='assets/base.png';sha256=$baseHash;media_type='image/png';role='pip';width_px=1024;height_px=1536;alt_text='base';visual_text_summary='no text';provider_or_capture='image2';postprocess=[ordered]@{completed_steps=@()};postprocess_record_path=$null;postprocess_record_sha256=$null;reuse_authorization_ref=$null;image2_runtime_profile='not_observable';evidence_parity_result='not_applicable';sidecar_path='records/base.sidecar.json';sidecar_sha256=$baseSidecarHash;generation_record_path='records/base.generation.json';generation_record_sha256=$generationHash;visual_review_ref=$null;asset_status='base_ready'}
$finalAsset=[ordered]@{asset_id='A-FINAL';asset_revision=1;visual_task_id='VT-1';asset_role='derived_rendition';source_class='generated_context';route_decision='image2_generated_context';parent_asset_ref=[ordered]@{asset_id='A-BASE';sha256=$baseHash};relative_path='assets/final.png';sha256=$finalHash;media_type='image/png';role='pip';width_px=1024;height_px=1536;alt_text='final';visual_text_summary='exact overlay';provider_or_capture='image2';postprocess=[ordered]@{completed_steps=@('deterministic_overlay')};postprocess_record_path='records/final.layout.json';postprocess_record_sha256=$postHash;reuse_authorization_ref=$null;image2_runtime_profile='not_observable';evidence_parity_result='not_applicable';sidecar_path='records/final.sidecar.json';sidecar_sha256=$finalSidecarHash;generation_record_path='records/base.generation.json';generation_record_sha256=$generationHash;visual_review_ref=[ordered]@{path='reviews/final.json';sha256=$reviewHash};asset_status='review_pass'}
$set=[pscustomobject]@{schema_id='taoge://schemas/r7/image-asset-set/v0.3';schema_version='0.3';image_asset_set_id='SET-1';coverage_ledger_ref=[ordered]@{artifact_id='LEDGER-1'};test_profile='production';finalize_requested_at='2026-07-16T08:00:00+08:00';assets=@([pscustomobject]$baseAsset,[pscustomobject]$finalAsset);delivery_bindings=@([pscustomobject]@{visual_task_id='VT-1';base_asset_ref=[ordered]@{asset_id='A-BASE';sha256=$baseHash};derived_rendition_refs=@([ordered]@{asset_id='A-FINAL';sha256=$finalHash});required_postprocess=@('deterministic_overlay');delivery_asset_ref=[ordered]@{asset_id='A-FINAL';sha256=$finalHash};finalize_status='ready_to_finalize'});provider_task_count=1;provider_attempt_count=1;provider_invocation_count=1;source_capture_attempt_count=0;postprocess_count=1;asset_set_status='materialized_waiting_finalize';next_skill='visual-asset-finalizer'}
Write-P0EvidenceAtomicText (Join-Path $work 'asset-set.json') (ConvertTo-P0EvidenceJsonText $set);$setDigest=Get-R7RuntimeHash (Join-Path $work 'asset-set.json')

$checks=[Collections.Generic.List[object]]::new()
function Add-Check([string]$Id,[bool]$Pass,[string]$Detail){$checks.Add([pscustomobject]@{id=$Id;pass=$Pass;detail=$Detail})}
$positive=@(Test-R7H7ImageAssetSetV03 $work $set);Add-Check 'H7-F01-final-overlay' ($positive.Count-eq0) ($positive-join',')
$built=New-R7H7ImageAssetDeliverySet $work $set $setDigest;Add-Check 'H7-F02-finalize-output' ($built.ExitCode-eq0-and$built.Data.delivery_asset_count-eq1-and$built.RecordWrites.Count-eq1-and$built.Data.finalize_record_refs[0].sha256-ne$null) ([string]$built.ResultCode)
if($built.ExitCode-eq0){foreach($recordWrite in @($built.RecordWrites)){Write-P0EvidenceAtomicText (Join-Path $work ([string]$recordWrite.RelativePath)) ([string]$recordWrite.Text)};Write-P0EvidenceAtomicText (Join-Path $work 'asset-delivery-set.json') (ConvertTo-P0EvidenceJsonText $built.Data)}
$badBase=($set|ConvertTo-Json -Depth 30|ConvertFrom-Json);$badBase.delivery_bindings[0].delivery_asset_ref=[pscustomobject]@{asset_id='A-BASE';sha256=$baseHash};$bad=@(Test-R7H7ImageAssetSetV03 $work $badBase);Add-Check 'H7-F03-base-not-final' (@($bad|Where-Object{$_-like'h7_base_used_as_final*'}).Count-eq1) ($bad-join',')
$missingReview=($set|ConvertTo-Json -Depth 30|ConvertFrom-Json);$missingReview.assets[1].visual_review_ref=$null;$bad=@(Test-R7H7ImageAssetSetV03 $work $missingReview);Add-Check 'H7-F04-review-required' (@($bad|Where-Object{$_-like'h7_delivery_visual_review_missing*'}).Count-eq1) ($bad-join',')
$viewport=[pscustomobject]@{schema_id='taoge://schemas/r7/viewport-acceptance/v0.2';schema_version='0.2';viewport_report_id='VIEWPORT-FIXTURE-001';session_id='r7-h7-fixture-work';final_delivery_ref=[pscustomobject]@{artifact_id='DELIVERY-1';sha256=('sha256:'+'e'*64)};html_path='deliverables/final-delivery.html';html_sha256=('sha256:'+'a'*64);browser_invocation_status='succeeded';layout_measurement_status='measured';technical_viewport_status='pass';overall_result='pass';profiles=@([pscustomobject]@{profile_id='desktop-1440x1000';overflow_offender_count=0;failed_image_count=0;failed_request_count=0;screenshot_sha256=('sha256:'+'b'*64)},[pscustomobject]@{profile_id='mobile-390x844';overflow_offender_count=0;failed_image_count=0;failed_request_count=0;screenshot_sha256=('sha256:'+'c'*64)});artifact_execution_contribution=[pscustomobject]@{manual_patch_detected=$false};workflow_autonomous_completion_count=0;autonomy_eligible=$false;warning_codes=@();created_at='2026-07-16T08:20:00+08:00';next_skill='business-delivery-acceptance'}
$vErrors=@(Test-R7H7ViewportV02 $viewport);Add-Check 'H7-F05-viewport-technical-only' ($vErrors.Count-eq0) ($vErrors-join',')
$badViewport=($viewport|ConvertTo-Json -Depth 10|ConvertFrom-Json);$badViewport|Add-Member visual_acceptance_status pass;$vErrors=@(Test-R7H7ViewportV02 $badViewport);Add-Check 'H7-F06-viewport-visual-forbidden' ($vErrors-contains'h7_viewport_visual_status_forbidden') ($vErrors-join',')
$dims=@('information_hierarchy','delivery_title_quality','final_asset_binding','readiness_truthfulness','visual_human_review','action_usability')|ForEach-Object{[pscustomobject]@{dimension_id=$_;status='pass';finding='verified'}}
$reviewPayload=[pscustomobject]@{schema_id='taoge://schemas/r7/business-delivery-acceptance/v0.1';schema_version='0.1';business_acceptance_id='BDA-FIXTURE-001';session_id='r7-h7-fixture-work';final_delivery_ref=[pscustomobject]@{artifact_id='DELIVERY-1';sha256=('sha256:'+'e'*64)};viewport_report_ref=[pscustomobject]@{artifact_id='VIEWPORT-1';sha256=('sha256:'+'f'*64)};html_sha256=$viewport.html_sha256;reviewer_type='codex_visual_review';review_evidence=[pscustomobject]@{desktop_screenshot_ref=[pscustomobject]@{sha256=$viewport.profiles[0].screenshot_sha256};mobile_screenshot_ref=[pscustomobject]@{sha256=$viewport.profiles[1].screenshot_sha256};actual_images_viewed=$true};dimensions=$dims;business_delivery_status='pass';blocking_issue_codes=@();warning_codes=@();reviewed_at='2026-07-16T08:30:00+08:00';next_skill='propagation-router'}
$bErrors=@(Test-R7H7BusinessDeliveryAcceptance $reviewPayload $viewport);Add-Check 'H7-F07-business-review' ($bErrors.Count-eq0) ($bErrors-join',')
$noView=($reviewPayload|ConvertTo-Json -Depth 10|ConvertFrom-Json);$noView.review_evidence.actual_images_viewed=$false;$bErrors=@(Test-R7H7BusinessDeliveryAcceptance $noView $viewport);Add-Check 'H7-F08-actual-view-required' ($bErrors-contains'h7_business_actual_visual_review_missing') ($bErrors-join',')
$wrongShot=($reviewPayload|ConvertTo-Json -Depth 10|ConvertFrom-Json);$wrongShot.review_evidence.mobile_screenshot_ref.sha256='sha256:'+'d'*64;$bErrors=@(Test-R7H7BusinessDeliveryAcceptance $wrongShot $viewport);Add-Check 'H7-F09-screenshot-binding' (@($bErrors|Where-Object{$_-like'h7_business_screenshot_binding_mismatch*'}).Count-eq1) ($bErrors-join',')

$built2=New-R7H7ImageAssetDeliverySet $work $set $setDigest;$stableA=Get-R7RuntimeObjectDigest $built.Data;$stableB=Get-R7RuntimeObjectDigest $built2.Data;Add-Check 'H7-F10-finalize-idempotent' ($stableA-eq$stableB) "$stableA/$stableB"
$missingEvidence=($set|ConvertTo-Json -Depth 30|ConvertFrom-Json);$missingEvidence.assets[1].sidecar_sha256='sha256:'+'0'*64;$bad=@(Test-R7H7ImageAssetSetV03 $work $missingEvidence);Add-Check 'H7-F11-evidence-digest' (@($bad|Where-Object{$_-like'h7_asset_evidence_digest_mismatch*'}).Count-eq1) ($bad-join',')
$badPost=($set|ConvertTo-Json -Depth 30|ConvertFrom-Json);$badPost.assets[1].postprocess_record_sha256='sha256:'+'1'*64;$bad=@(Test-R7H7ImageAssetSetV03 $work $badPost);Add-Check 'H7-F12-postprocess-digest' (@($bad|Where-Object{$_-like'h7_postprocess_record_digest_mismatch*'}).Count-eq1) ($bad-join',')
$warningReview=($reviewPayload|ConvertTo-Json -Depth 12|ConvertFrom-Json);$warningReview.dimensions[0].status='warning';$warningReview.business_delivery_status='pass';$bErrors=@(Test-R7H7BusinessDeliveryAcceptance $warningReview $viewport);Add-Check 'H7-F13-business-status-derivation' ($bErrors-contains'h7_business_status_derivation_invalid') ($bErrors-join',')
$registries=Get-R7RuntimeRegistries $ProjectRoot;$plan=New-R7RuntimePlan 'H7-PLAN-FIXTURE' 'direct_delivery_single_v0.4' $registries 'no_provider';$planErrors=@(Test-P0PlanContract $plan);$nodeOrder=@($plan.steps|Where-Object{$_.node_id-ne'session_plan'}|ForEach-Object{[string]$_.node_id});$finalizeIndex=[Array]::IndexOf([string[]]$nodeOrder,'visual_asset_finalize');$alignmentIndex=[Array]::IndexOf([string[]]$nodeOrder,'script_visual_alignment_h7');$viewportIndex=[Array]::IndexOf([string[]]$nodeOrder,'viewport_acceptance_h7');$businessIndex=[Array]::IndexOf([string[]]$nodeOrder,'business_delivery_acceptance');Add-Check 'H7-F14-plan-v10-order' ($planErrors.Count-eq0-and$finalizeIndex-gt0-and$alignmentIndex-eq$finalizeIndex+1-and$businessIndex-eq$viewportIndex+1) (($planErrors+$nodeOrder)-join',')
$fragment=Get-Content -Raw -Encoding UTF8 (Join-Path $ProjectRoot 'templates/final-delivery/final-delivery.v0.9.business-fragment.html');$ids=@('delivery-header','script-primary','visual-inserts-primary','platform-delivery-primary','warnings-primary','actions-primary','audit-details');$cursor=-1;$ordered=$true;foreach($id in $ids){$next=$fragment.IndexOf('id="'+$id+'"');if($next-le$cursor){$ordered=$false};$cursor=$next};Add-Check 'H7-F15-business-primary-order' ($ordered-and$fragment-notmatch'<details[^>]+open') 'primary_order_and_collapsed_audit'
$unit=[pscustomobject]@{display_order=1;platform_label='Douyin';cover_asset_path='assets/final.png';cover_sha256=$finalHash;cover_preview_path='assets/final.png';cover_preview_sha256=$finalHash;rendered_cover_text='cover';cover_title='cover';video_title='video';publish_description='body';hashtags=@('#usedcar')};$doc=[pscustomobject]@{platform_delivery_units=@($unit)};$htmlBase=Join-Path $work 'deliverables';[void](New-Item -ItemType Directory -Path $htmlBase -Force);$platformHtml=ConvertTo-R7H7PlatformUnitsHtml $doc $work $htmlBase;Add-Check 'H7-F16-no-duplicate-cover' ([regex]::Matches($platformHtml,'<img ').Count-eq1) ([string][regex]::Matches($platformHtml,'<img ').Count)
$baseReview=[ordered]@{schema_id='taoge://schemas/r3/visual-asset-review/v0.1';visual_review_status='pass';output_sha256=$baseHash;checks=@('text_accuracy','crop','readability','semantic_fit','safe_area')};Write-P0EvidenceAtomicText (Join-Path $work 'reviews/base.json') (ConvertTo-P0EvidenceJsonText $baseReview);$baseReviewHash=Get-R7RuntimeHash (Join-Path $work 'reviews/base.json');$baseOnly=($set|ConvertTo-Json -Depth 30|ConvertFrom-Json);$baseOnly.assets=@($baseOnly.assets[0]);$baseOnly.assets[0].visual_review_ref=[pscustomobject]@{path='reviews/base.json';sha256=$baseReviewHash};$baseOnly.assets[0].asset_status='review_pass';$baseOnly.delivery_bindings[0].derived_rendition_refs=@();$baseOnly.delivery_bindings[0].required_postprocess=@();$baseOnly.delivery_bindings[0].delivery_asset_ref=[pscustomobject]@{asset_id='A-BASE';sha256=$baseHash};$baseErrors=@(Test-R7H7ImageAssetSetV03 $work $baseOnly);Add-Check 'H7-F17-base-final-without-postprocess' ($baseErrors.Count-eq0) ($baseErrors-join',')
$runtimeText=Get-Content -Raw -Encoding UTF8 (Join-Path $ProjectRoot 'tools/R7CandidateRuntime.ps1');Add-Check 'H7-F18-runtime-v09-no-normalization' ($runtimeText.Contains('typed-components/v0.9')-and$runtimeText.Contains('compatibility_normalization_applied=$false')-and-not$runtimeText.Contains('temporary_candidate_compatibility')) 'candidate_v09_compiled_without_temporary_normalization'
$schemaFiles=@('templates/schema/r7/image-asset-set.v0.3.schema.json','templates/schema/r7/image-asset-delivery-set.v0.1.schema.json','templates/schema/r7/asset-finalize-record.v0.1.schema.json','templates/schema/final-delivery/typed-components.v0.9.schema.json','templates/schema/r7/viewport-acceptance.v0.2.schema.json','templates/schema/r7/business-delivery-acceptance.v0.1.schema.json','templates/schema/p0/session-execution-plan.v1.0.schema.json');$schemaParseErrors=[Collections.Generic.List[string]]::new();foreach($relative in $schemaFiles){try{$schema=Get-Content -Raw -Encoding UTF8 (Join-Path $ProjectRoot $relative)|ConvertFrom-Json;if([string]::IsNullOrWhiteSpace([string]$schema.'$id')){$schemaParseErrors.Add("schema_id_missing:$relative")}}catch{$schemaParseErrors.Add("schema_parse_error:$relative")}};Add-Check 'H7-F19-schema-parse' ($schemaParseErrors.Count-eq0) ($schemaParseErrors-join',')
$assetSchema=Get-Content -Raw -Encoding UTF8 (Join-Path $ProjectRoot 'templates/schema/r7/image-asset-set.v0.3.schema.json')|ConvertFrom-Json;$nodes=Read-WorkflowCompatibilityYamlAsset -ProjectRoot $ProjectRoot -AssetReference 'compatibility/legacy-r7/routes/r7-node-registry.yaml' -CallerRuntimeGeneration 'compile_time_compatibility';$routes=Read-WorkflowCompatibilityYamlAsset -ProjectRoot $ProjectRoot -AssetReference 'compatibility/legacy-r7/routes/r7-status-route-registry.yaml' -CallerRuntimeGeneration 'compile_time_compatibility';$commits=Read-WorkflowCompatibilityYamlAsset -ProjectRoot $ProjectRoot -AssetReference 'compatibility/legacy-r7/routes/r7-artifact-commit-registry.yaml' -CallerRuntimeGeneration 'compile_time_compatibility';$assetNode=@($nodes.nodes|Where-Object{$_.node_id-eq'visual_production_h7'})|Select-Object -First 1;$assetRoute=@($routes.nodes|Where-Object{$_.node_id-eq'visual_production_h7'})|Select-Object -First 1;$assetCommit=@($commits.profiles|Where-Object{$_.artifact_type-eq'image_asset_set'})|Select-Object -First 1;$schemaStatuses=@($assetSchema.properties.asset_set_status.enum|Sort-Object);$nodeStatuses=@($assetNode.allowed_result_statuses|Sort-Object);$routeStatuses=@(@($assetRoute.success)+@($assetRoute.warning)+@($assetRoute.waiting)+@($assetRoute.failure)|Sort-Object);$commitKeys=if($assetCommit.status_value_map-is[Collections.IDictionary]){@($assetCommit.status_value_map.Keys)}else{@($assetCommit.status_value_map.PSObject.Properties.Name)};$commitStatuses=@($commitKeys|Where-Object{$_-in$schemaStatuses}|Sort-Object);$statusParity=([string]::Join('|',$schemaStatuses)-eq[string]::Join('|',$nodeStatuses)-and[string]::Join('|',$schemaStatuses)-eq[string]::Join('|',$routeStatuses)-and[string]::Join('|',$schemaStatuses)-eq[string]::Join('|',$commitStatuses));Add-Check 'H7-F20-asset-status-six-layer-parity' $statusParity ([string]::Join('|',$schemaStatuses))
Write-P0EvidenceAtomicText (Join-Path $work 'viewport.json') (ConvertTo-P0EvidenceJsonText $viewport)
Write-P0EvidenceAtomicText (Join-Path $work 'business-acceptance.json') (ConvertTo-P0EvidenceJsonText $reviewPayload)
Write-P0EvidenceAtomicText (Join-Path $work 'plan-v1.0.json') (ConvertTo-P0EvidenceJsonText $plan)

$fail=@($checks|Where-Object{-not$_.pass});$report=[ordered]@{schema_id='taoge://reports/r7-h7-delivery-contract/v0.1';check_count=$checks.Count;pass_count=$checks.Count-$fail.Count;fail_count=$fail.Count;checks=[object[]]$checks.ToArray()};$reportPath=Join-Path $ProjectRoot 'state/checks/r7-h7-delivery-contract-report.json';Write-P0EvidenceAtomicText $reportPath (ConvertTo-P0EvidenceJsonText $report)
Write-Output "R7_H7_CHECKS=$($checks.Count)";Write-Output "R7_H7_FAILURES=$($fail.Count)";Write-Output "REPORT=$reportPath"
if($fail.Count){exit 1}
