param(
  [string]$WorkRoot='state/checks/r7-h4-candidate-work',
  [string]$HumanReportPath='state/checks/r7-h4-candidate-check-report.md',
  [string]$MachineReportPath='state/checks/r7-h4-candidate-check-report.json'
)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'WindowsRuntimeHelper.ps1')
. (Join-Path $PSScriptRoot 'R7ContractHelper.ps1')
. (Join-Path $PSScriptRoot 'R7SemanticRuntime.ps1')
. (Join-Path $PSScriptRoot 'R7CandidateRuntime.ps1')

function Resolve-R7H4Path([string]$Path){if([IO.Path]::IsPathRooted($Path)){return [IO.Path]::GetFullPath($Path)};return [IO.Path]::GetFullPath((Join-Path $script:ProjectRoot $Path))}
function New-R7H4Result([string]$Id,[string]$Expected,[string]$Actual,[string[]]$Errors=@()){[pscustomobject]@{fixture_id=$Id;expected_result=$Expected;actual_result=$Actual;expectation_met=($Expected-eq$Actual);errors=[object[]]@($Errors)}}
function Write-R7H4Pointer([string]$Session,[string]$Type,[string]$Id,[object]$Payload,[string]$Status){$rel="intermediate/r7/revisions/$Type/$Id.json";$path=Join-Path $Session $rel;Write-P0EvidenceAtomicText $path (ConvertTo-P0EvidenceJsonText $Payload);$digest=Get-R7RuntimeHash $path;$pointer=[ordered]@{schema_id='taoge://schemas/r7/semantic-current-pointer/v0.1';schema_version='0.1';artifact_type=$Type;artifact_id=$Id;revision=1;revision_path=$rel;sha256=$digest;status=$Status;task_envelope_id='FIXTURE-SEED';submission_id='FIXTURE-SEED';producer_event_id="EVT-FIXTURE-$Type";committed_at='2026-07-14T00:00:00Z'};Write-P0EvidenceAtomicText (Join-Path $Session "intermediate/r7/current/$Type.json") (ConvertTo-P0EvidenceJsonText $pointer)}
function Write-R7H4TinyPng([string]$Path){$parent=Split-Path -Parent $Path;if(-not(Test-Path $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};[IO.File]::WriteAllBytes($Path,[Convert]::FromBase64String('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='))}

function New-R7H4Session {
  param([string]$Root,[string]$SessionId,[ValidateSet('valid','global_review','wrong_hash')][string]$ReviewMode,[ValidateSet('single','multi_beat','missing_beat','non_contiguous','task_mismatch')][string]$OccurrenceMode='single')
  $session=Join-Path $Root $SessionId;New-Item -ItemType Directory -Path (Join-Path $session 'intermediate/p0') -Force|Out-Null
  $registries=Get-R7RuntimeRegistries $script:ProjectRoot;$plan=New-R7RuntimePlan $SessionId 'direct_delivery_single_v0.1' $registries;Write-P0EvidenceAtomicText (Join-Path $session 'intermediate/p0/session-execution-plan.json') (ConvertTo-P0EvidenceJsonText $plan)
  $eventPath=Join-Path $session 'intermediate/p0/execution-events.jsonl';$planDigest=Get-R7RuntimeHash (Join-Path $session 'intermediate/p0/session-execution-plan.json');[void](Write-P0EvidenceEvent -EventPath $eventPath -Plan $plan -StepId "STEP-$SessionId-session_plan" -EventType 'plan.created.v1' -EventSource runner -StateBefore ready -StateAfter succeeded -PayloadDigest $planDigest -IdempotencyKey "${SessionId}:plan" -ExpectedLastSequenceNo 0 -ResultCode fixture_seed -SafeSummary 'Fixture plan')
  foreach($step in @($plan.steps|Select-Object -Skip 1)){if($step.node_id -eq 'delivery_candidate_compile'){break};$events=@(Get-P0EvidenceEvents $eventPath);$source=if($step.step_kind -eq 'agent_required'){'agent_recorder'}elseif($step.step_kind -eq 'human_gate'){'human_recorder'}elseif($step.step_kind -eq 'external_side_effect'){'reconciler'}else{'runner'};[void](Write-P0EvidenceEvent -EventPath $eventPath -Plan $plan -StepId $step.step_id -EventType 'fixture.completed.v1' -EventSource $source -StateBefore ready -StateAfter succeeded -PayloadDigest (Get-R7RuntimeTextDigest ([string]$step.node_id)) -IdempotencyKey "${SessionId}:$($step.node_id)" -ExpectedLastSequenceNo $events.Count -ResultCode fixture_seed -SafeSummary 'Fixture prerequisite')}
  $projection=Update-P0StateProjection $session $plan $eventPath $true;if($projection.ExitCode-ne0){throw "projection_seed_failed:$($projection.ResultCode)"}
  $b=Read-R7JsonFile (Join-Path $script:ProjectRoot 'examples/r6-script-visual-fixtures/base-direct.json')
  if($OccurrenceMode-ne'single'){
    $b.coverage_ledger.coverage_records[0].primary_disposition='generate_visual';$b.coverage_ledger.coverage_records[0].primary_visual_task_id='VTASK-R6-001';$b.coverage_ledger.coverage_records[0].talking_head_advantage=$null
    $b.coverage_ledger.coverage_records[1].primary_disposition='reuse_visual_task';$b.coverage_ledger.coverage_records[1].primary_visual_task_id=$null;$b.coverage_ledger.coverage_records[1].reused_visual_task_id='VTASK-R6-001'
    $b.coverage_ledger.accepted_visual_tasks[0].covered_beat_ids=@('BEAT-R6-001','BEAT-R6-002');$b.coverage_ledger.visual_insert_occurrences[0].covered_beat_ids=@('BEAT-R6-001','BEAT-R6-002')
    if($OccurrenceMode-eq'missing_beat'){$b.coverage_ledger.visual_insert_occurrences[0].covered_beat_ids=@('BEAT-MISSING')}
    elseif($OccurrenceMode-eq'task_mismatch'){$b.coverage_ledger.accepted_visual_tasks[0].covered_beat_ids=@('BEAT-R6-002');$b.coverage_ledger.visual_insert_occurrences[0].covered_beat_ids=@('BEAT-R6-001')}
    elseif($OccurrenceMode-eq'non_contiguous'){
      $b.draft.body_text="甲`n乙`n丙";$third=($b.beat_map.beats[1]|ConvertTo-Json -Depth 20|ConvertFrom-Json);$third.beat_id='BEAT-R6-003';$third.order=3;$third.start_byte=8;$third.end_byte=11;$third.dependency_beat_ids=@('BEAT-R6-002');$b.beat_map.beats=@($b.beat_map.beats)+@($third)
      $thirdCoverage=($b.coverage_ledger.coverage_records[1]|ConvertTo-Json -Depth 20|ConvertFrom-Json);$thirdCoverage.coverage_record_id='COVER-R6-003';$thirdCoverage.beat_id='BEAT-R6-003';$b.coverage_ledger.coverage_records=@($b.coverage_ledger.coverage_records)+@($thirdCoverage)
      $b.coverage_ledger.accepted_visual_tasks[0].covered_beat_ids=@('BEAT-R6-001','BEAT-R6-003');$b.coverage_ledger.visual_insert_occurrences[0].covered_beat_ids=@('BEAT-R6-001','BEAT-R6-003')
    }
  }
  $intake=[ordered]@{intake_id="INTAKE-$SessionId";content_source_id="DIRECT-$SessionId";account=[ordered]@{account_display_name='Sample Account'};direct_content_status='direct_content_ready'}
  $brief=[ordered]@{brief_id=[string]$b.structure_plan.brief_id;content_goal='Validate a deterministic delivery candidate';core_promise=[string]$b.structure_plan.core_promise;brief_status='ready'}
  $package=[ordered]@{schema_id='taoge://schemas/r7/platform-package/v0.1';schema_version='0.1';platform_package_id="PK-$SessionId";draft_ref=[ordered]@{artifact_id=[string]$b.draft.draft_id};primary_platform='douyin';packages=@([ordered]@{platform='douyin';title='Sample video';cover_title='Sample cover';body_text='Sample delivery body';hashtags=@('#sample');notes=@()},[ordered]@{platform='xiaohongshu';title='Sample note';cover_title='Sample note cover';body_text='Sample note body';hashtags=@('#sample');notes=@()},[ordered]@{platform='wechat_channels';title='Sample channel';cover_title='Sample channel cover';body_text='Sample channel body';hashtags=@('#sample');notes=@()});package_status='package_pass_with_warnings';next_skill='platform-cover-composer'}
  $assetPath='assets/visuals/sample.png';Write-R7H4TinyPng (Join-Path $session $assetPath);$sidecar='assets/visuals/sample.record.json';Write-P0EvidenceAtomicText (Join-Path $session $sidecar) (ConvertTo-P0EvidenceJsonText ([ordered]@{record_id="REC-$SessionId";provider_invoked=$true}));$assetDigest=Get-R7RuntimeHash (Join-Path $session $assetPath)
  $assetSet=[ordered]@{schema_id='taoge://schemas/r7/image-asset-set/v0.1';schema_version='0.1';image_asset_set_id="ASSETSET-$SessionId";coverage_ledger_ref=[ordered]@{artifact_id=[string]$b.coverage_ledger.visual_coverage_ledger_id};assets=@([ordered]@{asset_id='ASSET-R6-001';visual_task_id='VTASK-R6-001';relative_path=$assetPath;sha256=$assetDigest;media_type='image/png';role='visual_insert';source_mode='provider_generated';provider_invoked=$true;width_px=1600;height_px=900;alt_text='Sample explanatory visual';visual_text_summary='A sample visual relation';sidecar_path=$sidecar;generation_record_path=$sidecar});provider_invocation_count=1;asset_set_status='ready_with_warnings';next_skill='script-visual-alignment-review'}
  $renditions=[Collections.Generic.List[object]]::new();$index=0;foreach($platform in @('douyin','xiaohongshu','wechat_channels')){$index++;$slug=switch($platform){douyin{'DY'}xiaohongshu{'XHS'}default{'SPH'}};$coverPath="assets/covers/$platform.png";$previewPath="assets/covers/$platform.preview.png";Write-R7H4TinyPng (Join-Path $session $coverPath);Write-R7H4TinyPng (Join-Path $session $previewPath);$coverDigest=Get-R7RuntimeHash (Join-Path $session $coverPath);$previewDigest=Get-R7RuntimeHash (Join-Path $session $previewPath);$reviewPath="assets/covers/$platform.review.json";$profile=(Get-R7CandidatePlatformProfile (Read-YamlFile (Join-Path $script:ProjectRoot 'routes/r7-delivery-presentation-registry.yaml')) $platform).surface_profile_id
    if($ReviewMode -eq 'global_review'){$review=[ordered]@{schema_id='taoge://assets/carried-forward-summary/v0.1';schema_version='0.1';summary_id="SUMMARY-$SessionId-$slug";output_sha256=$coverDigest;preview_sha256=$previewDigest;visual_review_status='pass'}}else{$review=[ordered]@{schema_id='taoge://schemas/r3/cover-visual-review/v0.1';schema_version='0.1';cover_visual_review_id="CVR-$SessionId-$slug";cover_rendition_id="CR-$SessionId-$slug";rendition_revision=1;surface_profile_id=[string]$profile;reviewer_type='codex_visual_review';observation_mode='fixture_raster_inspection';review_scope='fixture';output_sha256=$(if($ReviewMode -eq 'wrong_hash'){'sha256:'+('f'*64)}else{$coverDigest});preview_sha256=$previewDigest;visual_review_status='pass';findings=@();review_statement='Fixture cover observed';reviewed_at='2026-07-14T00:00:00Z'}}
    Write-P0EvidenceAtomicText (Join-Path $session $reviewPath) (ConvertTo-P0EvidenceJsonText $review);$renditions.Add([ordered]@{platform=$platform;asset_id="COVER-$SessionId-$slug";asset_path=$coverPath;sha256=$coverDigest;preview_path=$previewPath;review_ref=$reviewPath;review_status='visual_pass';target_canvas='1080x1920'})}
  $cover=[ordered]@{schema_id='taoge://schemas/r7/cover-composition/v0.1';schema_version='0.1';cover_composition_id="COVERSET-$SessionId";platform_package_ref=[ordered]@{artifact_id=[string]$package.platform_package_id};renditions=[object[]]$renditions.ToArray();cover_status='visual_pass';next_skill='final-delivery-builder'}
  $visualPackage=[ordered]@{schema_id='taoge://schemas/r7/visual-analysis-package/v0.1';schema_version='0.1';visual_coverage_ledger_id=[string]$b.coverage_ledger.visual_coverage_ledger_id;coverage_completeness_status='complete';visual_need_analysis=$b.visual_need_analysis;coverage_ledger=$b.coverage_ledger;next_skill='talking-head-image-pip'}
  $items=@(
    @('direct_content_intake',[string]$intake.intake_id,$intake,'intake_ready'),@('content_brief',[string]$brief.brief_id,$brief,'brief_pass'),@('short_video_structure_plan',[string]$b.structure_plan.structure_plan_id,$b.structure_plan,'structure_ready'),@('draft',[string]$b.draft.draft_id,$b.draft,'draft_preserved'),@('content_beat_map',[string]$b.beat_map.beat_map_id,$b.beat_map,'beat_map_complete'),@('script_design_review',[string]$b.script_review.script_design_review_id,$b.script_review,'ready_with_warnings'),@('content_revision_decision',[string]$b.revision_decision.content_revision_decision_id,$b.revision_decision,'keep_current'),@('visual_coverage_ledger',[string]$visualPackage.visual_coverage_ledger_id,$visualPackage,'coverage_complete'),@('image_asset_set',[string]$assetSet.image_asset_set_id,$assetSet,'ready_with_warnings'),@('script_visual_alignment_review',[string]$b.alignment_review.alignment_review_id,$b.alignment_review,'pass_with_warnings'),@('platform_package',[string]$package.platform_package_id,$package,'package_pass_with_warnings'),@('cover_composition',[string]$cover.cover_composition_id,$cover,'visual_pass'))
  foreach($item in $items){Write-R7H4Pointer $session $item[0] $item[1] $item[2] $item[3]}
  return $session
}

try{
  $script:ProjectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$work=Resolve-R7H4Path $WorkRoot;$human=Resolve-R7H4Path $HumanReportPath;$machine=Resolve-R7H4Path $MachineReportPath;foreach($p in @($work,(Split-Path -Parent $human),(Split-Path -Parent $machine))){if(-not(Test-Path $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null}};$run=Join-Path $work ('RUN-'+(Get-Date -Format 'yyyyMMdd-HHmmss')+'-'+[guid]::NewGuid().ToString('N').Substring(0,6));New-Item -ItemType Directory $run|Out-Null;$results=[Collections.Generic.List[object]]::new()
  $valid=New-R7H4Session $run 'R7-F09-F13' valid;$compile=Invoke-R7CandidateCompile $script:ProjectRoot $valid;$candidatePointer=Join-Path $valid 'intermediate/r7/current/final_delivery_render_candidate.json';$candidate=if(Test-Path $candidatePointer){(Get-R7CandidateCurrentArtifact $valid 'final_delivery_render_candidate').Payload}else{$null};$errorsValid=[Collections.Generic.List[string]]::new();if($compile.ExitCode-ne0){$errorsValid.AddRange([string[]]@($compile.Errors))};if($null-eq$candidate){$errorsValid.Add('candidate_missing')}else{if($candidate.compiler_provenance.producer-ne'deterministic_compiler'){$errorsValid.Add('producer_not_deterministic')};if(@($candidate.source_map).Count-ne12){$errorsValid.Add('source_map_count_invalid')};if($candidate.artifact_execution_contribution.manual_patch_detected){$errorsValid.Add('manual_patch_false_positive')}}
  $render=if($compile.ExitCode-eq0){Invoke-R7DeliveryRender $script:ProjectRoot $valid}else{$compile};if($render.ExitCode-ne0){$errorsValid.AddRange([string[]]@($render.Errors))};$htmlPath=Join-Path $valid 'deliverables/final-delivery.html';if(-not(Test-Path $htmlPath)){$errorsValid.Add('v06_html_missing')}else{$html=Get-Content -Raw -Encoding UTF8 $htmlPath;if($html-notmatch'data-template-version="0.6.0"'-or$html-notmatch'id="execution-transparency"'){$errorsValid.Add('v06_html_contract_missing')}};if(-not(Test-Path (Join-Path $valid 'deliverables/p0/render-receipt.json'))){$errorsValid.Add('v06_receipt_missing')}
  $events=@(Get-P0EvidenceEvents (Join-Path $valid 'intermediate/p0/execution-events.jsonl'));if(@($events|Where-Object{$_.event_type-eq'deterministic.result_committed.v1'-and$_.step_id-like'*-delivery_candidate_compile'}).Count-ne1){$errorsValid.Add('candidate_event_missing')};if(@($events|Where-Object{$_.event_type-eq'deterministic.result_committed.v1'-and$_.step_id-like'*-final_delivery_render'}).Count-ne1){$errorsValid.Add('renderer_event_missing')};$results.Add((New-R7H4Result 'R7-F09' candidate_compile_pass $(if($errorsValid.Count){'fail'}else{'candidate_compile_pass'}) $errorsValid.ToArray()));$results.Add((New-R7H4Result 'R7-F13' source_map_digest_event_auto $(if($errorsValid.Count){'fail'}else{'source_map_digest_event_auto'}) $errorsValid.ToArray()))
  $global=New-R7H4Session $run 'R7-F10' global_review;$r10=Invoke-R7CandidateCompile $script:ProjectRoot $global;$results.Add((New-R7H4Result 'R7-F10' asset_review_binding_error ([string]$r10.ResultCode) @($r10.Errors)))
  $wrong=New-R7H4Session $run 'R7-F11' wrong_hash;$r11=Invoke-R7CandidateCompile $script:ProjectRoot $wrong;$results.Add((New-R7H4Result 'R7-F11' asset_review_binding_error ([string]$r11.ResultCode) @($r11.Errors)))
  $actions=Read-YamlFile (Join-Path $script:ProjectRoot 'routes/r7-action-registry.yaml');$actual12=if('regenerate_visual' -notin @($actions.actions.action_code)){'enum_registry_error'}else{'fail'};$results.Add((New-R7H4Result 'R7-F12' enum_registry_error $actual12 @()))
  $multi=New-R7H4Session $run 'R7-F30' valid multi_beat
  $r30=Invoke-R7CandidateCompile $script:ProjectRoot $multi
  $candidate30=if($r30.ExitCode -eq 0){(Get-R7CandidateCurrentArtifact $multi 'final_delivery_render_candidate').Payload}else{$null}
  $occurrenceProjection=@();$ownerCard=$null;$reuseCard=$null
  if($null -ne $candidate30){
    $occurrenceProjection=@($candidate30.delivery_payload.content_beat_cards|ForEach-Object{@($_.occurrence_ids)})
    $ownerCard=@($candidate30.delivery_payload.content_beat_cards|Where-Object{$_.beat_id -eq 'BEAT-R6-001'})|Select-Object -First 1
    $reuseCard=@($candidate30.delivery_payload.content_beat_cards|Where-Object{$_.beat_id -eq 'BEAT-R6-002'})|Select-Object -First 1
  }
  $pass30=($r30.ExitCode -eq 0 -and $occurrenceProjection.Count -eq 1 -and @($ownerCard.occurrence_ids) -contains 'OCC-R6-001' -and @($reuseCard.occurrence_ids).Count -eq 0 -and @($reuseCard.visual_task_ids) -contains 'VTASK-R6-001')
  $results.Add((New-R7H4Result 'R7-F30' multi_beat_occurrence_single_owner $(if($pass30){'multi_beat_occurrence_single_owner'}else{'fail'}) @($r30.Errors)))
  foreach($negative in @(@('R7-F31','missing_beat','covered_beat_missing'),@('R7-F32','non_contiguous','covered_beats_non_contiguous'),@('R7-F33','task_mismatch','task_coverage_mismatch'))){
    $fixture=New-R7H4Session $run $negative[0] valid $negative[1]
    $result=Invoke-R7CandidateCompile $script:ProjectRoot $fixture
    $matched=@($result.Errors|Where-Object{$_ -like ("*candidate_occurrence_contract_error:$($negative[2])*")}).Count -gt 0
    $results.Add((New-R7H4Result $negative[0] candidate_occurrence_contract_error $(if($matched){'candidate_occurrence_contract_error'}else{[string]$result.ResultCode}) @($result.Errors)))
  }
  $mismatch=@($results|Where-Object{-not$_.expectation_met});$report=[ordered]@{r7_h4_candidate_check_report=[ordered]@{check_run_id='R7-H4-'+(Get-Date -Format 'yyyyMMdd-HHmmss');overall_result=$(if($mismatch.Count){'fail'}else{'pass'});exit_code=$(if($mismatch.Count){1}else{0});fixture_count=$results.Count;mismatch_count=$mismatch.Count;not_tested_scope=@('r7_h5_viewport','real_account','provider','network','publishing');checks=[object[]]$results.ToArray()}};Write-TaogeUtf8NoBomJson $machine $report 30;$lines=@('# R7-H4 Candidate Runtime Check','',"overall_result: $($report.r7_h4_candidate_check_report.overall_result)",'','| Fixture | Expected | Actual | Matched | Errors |','|---|---|---|---:|---|');foreach($x in $results){$lines+="| $($x.fixture_id) | $($x.expected_result) | $($x.actual_result) | $($x.expectation_met) | $([string]::Join(';',@($x.errors))) |"};Write-TaogeUtf8NoBomLines $human $lines
  if($mismatch.Count){Write-Output 'R7_H4_CANDIDATE_CHECK_RESULT=fail';foreach($x in $mismatch){Write-Output "R7_H4_ERROR=$($x.fixture_id):$([string]::Join(';',@($x.errors)))"};exit 1};Write-Output 'R7_H4_CANDIDATE_CHECK_RESULT=pass';Write-Output "R7_H4_FIXTURE_COUNT=$($results.Count)";exit 0
}catch{Write-Error("{0} at line {1}: {2}"-f$_.Exception.Message,$_.InvocationInfo.ScriptLineNumber,$_.InvocationInfo.Line);exit 3}
