param(
  [string]$WorkRoot='state/checks/r7-h6b-freshness-work',
  [string]$HumanReportPath='state/checks/r7-h6b-freshness-report.md',
  [string]$MachineReportPath='state/checks/r7-h6b-freshness-report.json'
)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'WindowsRuntimeHelper.ps1')
. (Join-Path $PSScriptRoot 'R7ContractHelper.ps1')
. (Join-Path $PSScriptRoot 'R7SemanticRuntime.ps1')
. (Join-Path $PSScriptRoot 'R7CandidateRuntime.ps1')
. (Join-Path $PSScriptRoot 'R7HotspotContractHelper.ps1')
. (Join-Path $PSScriptRoot 'R7HotspotFreshnessRuntime.ps1')

function Resolve-H6BPath([string]$Path){if([IO.Path]::IsPathRooted($Path)){return [IO.Path]::GetFullPath($Path)};return [IO.Path]::GetFullPath((Join-Path $script:ProjectRoot $Path))}
function Copy-H6BObject([object]$Value){return($Value|ConvertTo-Json -Depth 90|ConvertFrom-Json)}
function Add-H6BResult([Collections.Generic.List[object]]$Results,[string]$Id,[bool]$Passed,[string]$Actual,[string[]]$Errors=@()){$Results.Add([pscustomobject]@{fixture_id=$Id;expected_result='pass';actual_result=$(if($Passed){'pass'}else{$Actual});expectation_met=$Passed;errors=[object[]]$Errors})}
function New-H6BReview([string]$Change,[string]$Identity='same_topic'){
  $attempt=[ordered]@{attempt_id='ATT-FRESH-001';attempt_status='succeeded';source_record_id='SRC-001';attempted_at='2026-07-15T02:00:00Z';failure_category=$null};$deltas=@();$packet=$null;$packetDigest=$null;$map=[ordered]@{}
  if($Change-eq'observation_refresh'){$delta=[ordered]@{source_record_id='SRC-001';change_type='metadata_refresh';before_digest='sha256:'+('1'*64);after_digest='sha256:'+('2'*64);component_digest='sha256:'+('3'*64)};$deltas=@($delta);$map['SRC-001']=$delta.component_digest}
  if($Change-in@('material_fact_update','topic_reversal_or_identity_change')){$claim=[ordered]@{claim_id='CLM-001';claim_type='factual_claim';claim_evidence_status='supported';source_record_ids=@('SRC-001');source_independence_status='single_source';source_support_basis='authoritative_primary';allowed_expression='assert_as_fact'};$packet=[ordered]@{topic_evidence_packet_id='EVID-NEW-001';event_fact_status='verified';propagation_status='observed';risk_level='medium';claims=@($claim)};$packetDigest=Get-R7HotspotCanonicalDigest $packet;$map['replacement_evidence_packet']=$packetDigest}
  return [pscustomobject]@{schema_id='taoge://schemas/r7/topic-freshness-review/v0.1';schema_version='0.1.0';freshness_review_id='FRESH-001';freshness_review_revision=1;selected_topic_source_ref=[ordered]@{artifact_id='STS-001';revision=1;sha256='sha256:'+('a'*64)};review_status='complete';change_class=$Change;topic_identity_status=$Identity;checked_at='2026-07-15T02:00:00Z';source_attempt_refs=@($attempt);source_record_deltas=[object[]]$deltas;replacement_evidence_packet=$packet;replacement_evidence_packet_digest=$packetDigest;component_digest_map=$map;review_reason='Offline deterministic fixture review.'}
}

try{
  $script:ProjectRoot=(Resolve-Path(Join-Path $PSScriptRoot '..')).Path;$work=Resolve-H6BPath $WorkRoot;$human=Resolve-H6BPath $HumanReportPath;$machine=Resolve-H6BPath $MachineReportPath;foreach($p in @($work,(Split-Path -Parent $human),(Split-Path -Parent $machine))){if(-not(Test-Path $p)){New-Item -ItemType Directory -Path $p -Force|Out-Null}}
  $suite=Read-R7JsonFile(Join-Path $script:ProjectRoot 'examples/r7-h6b-freshness-fixtures/fixture-cases.json');$results=[Collections.Generic.List[object]]::new();$ref=[ordered]@{artifact_id='STS-001';revision=1;sha256='sha256:'+('a'*64)};$reviewRef=[ordered]@{artifact_id='FRESH-001';revision=1;sha256='sha256:'+('b'*64)}
  $source=[pscustomobject]@{schema_id='taoge://schemas/r7/selected-topic-source/v0.1';schema_version='0.1.0';selected_topic_source_id='STS-001';selected_topic_source_revision=1;content_origin='hotspot_selected_topic';account_snapshot_ref=[ordered]@{artifact_id='SNAP-001';revision=1;sha256='sha256:'+('c'*64)};radar_policy_ref=[ordered]@{artifact_id='POL-001';revision=1;sha256='sha256:'+('d'*64)};research_set_ref=[ordered]@{artifact_id='SET-001';revision=1;sha256='sha256:'+('e'*64)};selection_panel_ref=[ordered]@{artifact_id='PANEL-001';revision=1;sha256='sha256:'+('f'*64)};selection_decision_ref=[ordered]@{artifact_id='DEC-001';revision=1;sha256='sha256:'+('1'*64)};event_ref=[ordered]@{};candidate_ref=[ordered]@{};topic_option_ref=[ordered]@{};topic_evidence_packet_ref=[ordered]@{};monitoring_source_record_refs=@();latest_freshness_review_ref=$null;freshness_policy=[ordered]@{policy_mode='always_revalidate_before_delivery';max_age_hours=$null;threshold_basis=$null;policy_basis_refs=@();event_triggers=@();fallback_reason='no_trusted_duration_or_trigger_policy'};selection_freshness_status='current';digest_basis_version='selected-topic-source-digest-v0.1';content_semantic_digest='sha256:'+('2'*64);monitoring_digest='sha256:'+('3'*64);selected_source_status='ready_for_brief';selected_at='2026-07-15T01:00:00Z'}
  $registries=Get-R7RuntimeRegistries $script:ProjectRoot;$plan=New-R7RuntimePlan 'S-R7-H6B-FIXTURE' 'hotspot_to_delivery_single_v0.2' $registries

  $observation=New-H6BReview 'observation_refresh';$observationErrors=@(Test-R7TopicFreshnessReview $observation $ref);$observationApply=New-R7AppliedSelectedTopicSource $source $ref $observation $reviewRef;$observationAppliedErrors=@(Test-R7AppliedSelectedTopicSourceContract $source $observationApply.Payload $observation $reviewRef);Add-H6BResult $results 'R7-F42' ($observationErrors.Count-eq0-and$observationApply.ResultStatus-eq'monitoring_applied'-and$observationAppliedErrors.Count-eq0) 'observation_refresh_failed' @($observationErrors+$observationApply.Errors+$observationAppliedErrors)
  $material=New-H6BReview 'material_fact_update';$materialApply=New-R7AppliedSelectedTopicSource $source $ref $material $reviewRef;$materialPlan=New-R7HotspotReplanPlan $plan $materialApply.RestartNodeId $materialApply.ResultStatus @([ordered]@{artifact_id='STS-001';status='carried_forward'}) @();$materialBranch=@($materialPlan.steps|Where-Object{$_.step_id-match'-R2$'});Add-H6BResult $results 'R7-F43' ($materialApply.ResultStatus-eq'semantic_update_replan'-and$materialPlan.restart_from_node_id-eq'hotspot_content_brief'-and$materialBranch[0].node_id-eq'hotspot_content_brief') 'material_replan_failed' @($materialApply.Errors)
  $reversal=New-H6BReview 'topic_reversal_or_identity_change' 'identity_changed';$reversalApply=New-R7AppliedSelectedTopicSource $source $ref $reversal $reviewRef;$previousRequest=[pscustomobject]@{Ref=[ordered]@{artifact_id='HRQ-001';revision=1;sha256='sha256:'+('7'*64)};Payload=[pscustomobject]@{account_identity_ref=[ordered]@{artifact_id='IDENTITY-001';revision=1;sha256='sha256:'+('6'*64)}}};$revalidationRequest=New-R7HotspotRevalidationRequest $previousRequest $reversalApply.Payload $reversal $reviewRef;$reversalPlan=New-R7HotspotReplanPlan $plan $reversalApply.RestartNodeId $reversalApply.ResultStatus @([ordered]@{artifact_id='STS-001';status='carried_forward'},[ordered]@{artifact_id=$revalidationRequest.research_request_id;status='carried_forward'}) @();$reversalBranch=@($reversalPlan.steps|Where-Object{$_.step_id-match'-R2$'});Add-H6BResult $results 'R7-F44' ($reversalApply.ResultStatus-eq'topic_revalidation_replan'-and$reversalBranch[0].node_id-eq'hotspot_research'-and$revalidationRequest.request_mode-eq'revalidation_after_reversal') 'reversal_replan_failed' @($reversalApply.Errors)
  $unsafe=Copy-H6BObject $material.replacement_evidence_packet;$unsafe.risk_level='high';$unsafe.claims[0].allowed_expression='assert_as_fact';$unsafeErrors=@(Test-R7HotspotEvidencePacket $unsafe);Add-H6BResult $results 'R7-F46' ($unsafeErrors.Count-gt0) 'unsafe_allegation_not_blocked' $unsafeErrors
  $captureFail=New-H6BReview 'no_material_change';$captureFail.source_attempt_refs[0].attempt_status='failed';$captureFail.source_attempt_refs[0].failure_category='tool';$captureErrors=@(Test-R7TopicFreshnessReview $captureFail $ref);$captureApply=New-R7AppliedSelectedTopicSource $source $ref $captureFail $reviewRef;Add-H6BResult $results 'R7-F47' ($captureErrors.Count-eq0-and$captureApply.Payload.content_semantic_digest-eq$source.content_semantic_digest-and$captureFail.source_attempt_refs.Count-eq1) 'capture_failure_semantics_invalid' @($captureErrors+$captureApply.Errors)
  $fragmentPath=Resolve-WorkflowCompatibilityAsset -ProjectRoot $script:ProjectRoot -AssetReference 'compatibility/legacy-r7/templates/final-delivery/final-delivery.v0.7.hotspot-fragment.html' -CallerRuntimeGeneration 'compile_time_compatibility';$fragment=Get-Content -Raw $fragmentPath;$runtimeText=Get-Content -Raw(Join-Path $script:ProjectRoot 'tools/R7CandidateRuntime.ps1');Add-H6BResult $results 'R7-F50' ($fragment-match'source-currentness'-and$runtimeText-match'event_fact_status'-and$runtimeText-match'propagation_status'-and$runtimeText-match'risk_level'-and$runtimeText-match'review.checked_at'-and$runtimeText-match'source_url') 'hotspot_html_contract_missing' @()
  $policyErrors=@(Test-R7HotspotFreshnessPolicy $source.freshness_policy);Add-H6BResult $results 'R7-F62' ($policyErrors.Count-eq0-and$source.freshness_policy.policy_mode-eq'always_revalidate_before_delivery') 'fallback_policy_invalid' $policyErrors
  $waiting=New-H6BReview 'no_material_change';$waiting.review_status='waiting_external';$waiting.change_class='not_assessed';$waiting.topic_identity_status='not_assessed';$waiting.source_record_deltas=@();$waiting.replacement_evidence_packet=$null;$waiting.replacement_evidence_packet_digest=$null;$waiting.component_digest_map=[ordered]@{};$waitingErrors=@(Test-R7TopicFreshnessReview $waiting $ref);$waitingApply=New-R7AppliedSelectedTopicSource $source $ref $waiting $reviewRef;Add-H6BResult $results 'R7-F63' ($waitingErrors.Count-eq0-and$waitingApply.Errors.Count-gt0-and$null-eq$waitingApply.Payload) 'waiting_review_advanced' @($waitingErrors+$waitingApply.Errors)
  $badAfter=Copy-H6BObject $observationApply.Payload;$badAfter.content_semantic_digest='sha256:'+('9'*64);$badAfterErrors=@(Test-R7AppliedSelectedTopicSourceContract $source $badAfter $observation $reviewRef);Add-H6BResult $results 'R7-F64' (@($badAfterErrors|Where-Object{$_-eq'freshness_monitoring_semantic_digest_changed'}).Count-eq1) 'semantic_change_not_blocked' $badAfterErrors
  $newCandidate=@($materialPlan.steps|Where-Object{$_.node_id-eq'delivery_candidate_compile'-and$_.step_id-match'-R2$'});Add-H6BResult $results 'R7-F65' ($newCandidate.Count-eq1-and$materialPlan.restart_from_node_id-eq'hotspot_content_brief') 'old_plan_candidate_not_invalidated' @()
  Add-H6BResult $results 'R7-F66' ($reversalBranch[0].node_id-eq'hotspot_research'-and$revalidationRequest.triggering_decision_ref-eq$null-and$revalidationRequest.triggering_freshness_review_ref.artifact_id-eq$reviewRef.artifact_id) 'old_decision_reused' @()
  $directContext=[pscustomobject]@{content_origin='user_supplied_draft';content_source_ref=$ref;research_set_ref=$source.research_set_ref;selection_decision_ref=$null;selected_topic_source_ref=$null;freshness_review_ref=$null};$directErrors=@(Test-R7ContentSourceContextV07 $directContext);Add-H6BResult $results 'R7-F68' (@($directErrors|Where-Object{$_-like'content_source_context_direct_ref_forbidden*'}).Count-eq1) 'direct_union_not_blocked' $directErrors
  Add-H6BResult $results 'R7-F69' ((Get-R7VisualCapabilityDisposition 2 0 $false)-eq'waiting_assets') 'provider_unavailable_not_waiting' @()
  $badReplacement=Copy-H6BObject $material;$badReplacement.replacement_evidence_packet_digest='sha256:'+('8'*64);$badReplacementErrors=@(Test-R7TopicFreshnessReview $badReplacement $ref);$badIdentity=Copy-H6BObject $material;$badIdentity.topic_identity_status='identity_changed';$badIdentityErrors=@(Test-R7TopicFreshnessReview $badIdentity $ref);Add-H6BResult $results 'R7-F78' ($badReplacementErrors.Count-gt0-and$badIdentityErrors.Count-gt0) 'replacement_or_identity_not_blocked' @($badReplacementErrors+$badIdentityErrors)
  $planAgain=New-R7HotspotReplanPlan $plan $materialApply.RestartNodeId $materialApply.ResultStatus @([ordered]@{artifact_id='STS-001';status='carried_forward'}) @();Add-H6BResult $results 'R7-F79' ((Get-R7RuntimeObjectDigest $materialPlan)-eq(Get-R7RuntimeObjectDigest $planAgain)) 'replan_not_idempotent' @()
  $selectedItem=[pscustomobject]@{Pointer=[pscustomobject]@{artifact_id='STS-001';revision=2;sha256='sha256:'+('4'*64)};Sha256='sha256:'+('4'*64);Payload=$observationApply.Payload};$selectedItem.Payload.latest_freshness_review_ref=$reviewRef;$freshItem=[pscustomobject]@{Pointer=[pscustomobject]@{artifact_id='FRESH-OTHER';revision=1;sha256='sha256:'+('5'*64)};Sha256='sha256:'+('5'*64);Payload=$observation};$bindingErrors=@(Test-R7CandidateFreshnessBinding $selectedItem $freshItem);Add-H6BResult $results 'R7-F81' ($bindingErrors.Count-gt0) 'freshness_binding_not_blocked' $bindingErrors
  $badAccounting=Copy-H6BObject $materialPlan;$badAccounting.carried_forward_artifact_refs=@([pscustomobject]@{artifact_id='STS-001';status='new_succeeded'});$badAccounting.steps+=$badAccounting.steps[-1];$accountingErrors=@(Test-R7HotspotReplanAccounting $plan $badAccounting);Add-H6BResult $results 'R7-F82' ($accountingErrors.Count-ge2) 'replan_accounting_not_blocked' $accountingErrors

  $known=@($suite.cases|ForEach-Object{[string]$_.fixture_id});foreach($result in $results){if($result.fixture_id-notin$known){$result.expectation_met=$false;$result.actual_result='fixture_not_registered'}};$mismatches=@($results|Where-Object{-not$_.expectation_met});$report=[ordered]@{r7_h6b_freshness_report=[ordered]@{check_run_id='R7-H6B-'+(Get-Date -Format 'yyyyMMdd-HHmmss');overall_result=$(if($mismatches.Count){'fail'}else{'pass'});exit_code=$(if($mismatches.Count){1}else{0});fixture_count=$results.Count;mismatch_count=$mismatches.Count;not_tested_scope=@('real_network_research','real_source_capture','image_provider','account_login','publishing','h6c_private_regression','l3_real_evidence');checks=[object[]]$results.ToArray()}};Write-TaogeUtf8NoBomJson $machine $report 80;$lines=@('# R7-H6B Freshness, Replan and Delivery Check','',"overall_result: $($report.r7_h6b_freshness_report.overall_result)","fixture_count: $($results.Count)",'','| Fixture | Actual | Matched | Errors |','|---|---|---:|---|');foreach($item in $results){$lines+="| $($item.fixture_id) | $($item.actual_result) | $($item.expectation_met) | $([string]::Join(';',@($item.errors))) |"};Write-TaogeUtf8NoBomLines $human $lines
  if($mismatches.Count){Write-Output 'R7_H6B_FRESHNESS_RESULT=fail';foreach($item in $mismatches){Write-Output "R7_H6B_ERROR=$($item.fixture_id):$($item.actual_result):$([string]::Join(';',@($item.errors)))"};exit 1};Write-Output 'R7_H6B_FRESHNESS_RESULT=pass';Write-Output "R7_H6B_FIXTURE_COUNT=$($results.Count)";exit 0
}catch{Write-Error("{0} at line {1}: {2}"-f$_.Exception.Message,$_.InvocationInfo.ScriptLineNumber,$_.InvocationInfo.Line);exit 3}
