param(
  [string]$ProjectRoot='',
  [string]$ReportPath='state/checks/doc-governance-report.json'
)
$ErrorActionPreference='Stop';Set-StrictMode -Version 2.0
function Add-DocCheck([Collections.Generic.List[object]]$Checks,[Collections.Generic.List[string]]$Errors,[string]$Id,[bool]$Pass,[string]$Evidence){$Checks.Add([ordered]@{check_id=$Id;result=$(if($Pass){'pass'}else{'fail'});evidence=$Evidence});if(-not$Pass){$Errors.Add($Id)}}
function Get-HeadingSlug([string]$Heading){$value=$Heading.Trim().ToLowerInvariant();$value=[regex]::Replace($value,'[^\p{L}\p{Nd}\s-]','');$value=[regex]::Replace($value,'\s+','-');$value=[regex]::Replace($value,'-+','-');$value.Trim('-')}
try{
  if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)};$root=(Resolve-Path -LiteralPath $ProjectRoot).Path
  $checks=[Collections.Generic.List[object]]::new();$errors=[Collections.Generic.List[string]]::new()
  $requiredIndexes=@('docs/README.md','docs/product/README.md','docs/product/checks/README.md','docs/reference/README.md','docs/governance/README.md','docs/explanation/README.md','docs/how-to/README.md','docs/tutorials/README.md','skills/README.md','templates/README.md','examples/README.md','tools/README.md','routes/README.md','state/README.md');if(Test-Path -LiteralPath (Join-Path $root 'objects')){$requiredIndexes+='objects/README.md'}
  $missingIndexes=@($requiredIndexes|Where-Object{-not(Test-Path -LiteralPath (Join-Path $root $_) -PathType Leaf)});Add-DocCheck $checks $errors 'DOC-GOV-001-SECTION-INDEXES' ($missingIndexes.Count-eq0) ([string]::Join('|',@($missingIndexes)))

  $coverageGroups=@(
    @{dir='docs/product';index='docs/product/README.md';exclude=@('README.md')},
    @{dir='docs/product/checks';index='docs/product/checks/README.md';exclude=@('README.md')},
    @{dir='docs/reference';index='docs/reference/README.md';exclude=@('README.md')},
    @{dir='docs/explanation';index='docs/explanation/README.md';exclude=@('README.md')},
    @{dir='docs/how-to';index='docs/how-to/README.md';exclude=@('README.md')}
  );$coverageMissing=[Collections.Generic.List[string]]::new()
  $isGitRepo=Test-Path -LiteralPath (Join-Path $root '.git')
  foreach($group in $coverageGroups){$indexText=Get-Content -LiteralPath (Join-Path $root $group.index) -Raw -Encoding UTF8;$files=if($isGitRepo){@(& git -C $root ls-files "$($group.dir)/*.md"|Where-Object{(Split-Path -Parent $_).Replace('\','/')-eq$group.dir})}else{@(Get-ChildItem -LiteralPath (Join-Path $root $group.dir) -Filter '*.md' -File|ForEach-Object{$_.FullName.Substring($root.Length+1).Replace('\','/')})};foreach($file in $files){$name=[IO.Path]::GetFileName($file);if($group.exclude-contains$name){continue};if(-not$indexText.Contains($name)){$coverageMissing.Add($file)}}}
  Add-DocCheck $checks $errors 'DOC-GOV-002-DIRECT-DOC-COVERAGE' ($coverageMissing.Count-eq0) ([string]::Join('|',@($coverageMissing)))

  $tutorialIndex=Get-Content -LiteralPath (Join-Path $root 'docs/tutorials/README.md') -Raw -Encoding UTF8;$tutorialMissing=[Collections.Generic.List[string]]::new();foreach($dir in @(Get-ChildItem -LiteralPath (Join-Path $root 'docs/tutorials') -Directory)){if(-not(Test-Path -LiteralPath (Join-Path $dir.FullName 'README.md'))-or-not$tutorialIndex.Contains($dir.Name)){$tutorialMissing.Add($dir.Name)}}
  $skillIndex=Get-Content -LiteralPath (Join-Path $root 'skills/README.md') -Raw -Encoding UTF8;$skillMissing=[Collections.Generic.List[string]]::new();foreach($dir in @(Get-ChildItem -LiteralPath (Join-Path $root 'skills') -Directory)){if((Test-Path -LiteralPath (Join-Path $dir.FullName 'SKILL.md'))-and-not$skillIndex.Contains($dir.Name)){$skillMissing.Add($dir.Name)}}
  Add-DocCheck $checks $errors 'DOC-GOV-003-DIRECTORY-COVERAGE' ($tutorialMissing.Count-eq0-and$skillMissing.Count-eq0) "tutorial=$([string]::Join(',',@($tutorialMissing)));skills=$([string]::Join(',',@($skillMissing)))"

  $rootReadme=Get-Content -LiteralPath (Join-Path $root 'README.md') -Raw -Encoding UTF8;$projectMap=Get-Content -LiteralPath (Join-Path $root 'PROJECT_MAP.md') -Raw -Encoding UTF8;$rootTokens=@('docs/README.md','docs/product/README.md','docs/reference/README.md','skills/README.md','templates/README.md');$rootMissing=@($rootTokens|Where-Object{-not($rootReadme.Contains($_)-or$projectMap.Contains($_))});Add-DocCheck $checks $errors 'DOC-GOV-004-ROOT-FAST-PATH' ($rootMissing.Count-eq0-and$rootReadme.Contains('ai-reading-boundary')) ([string]::Join('|',@($rootMissing)))

  $allowedRootMarkdown=@('README.md','AGENTS.md','PROJECT_MAP.md','STATUS.md','CHANGELOG.md','RELEASE_NOTES.md','CONTACT.md','SECURITY.md','CONTRIBUTING.md','CODE_OF_CONDUCT.md','NOTICE.md','INSTALL.md','UPDATE.md','release-checklist.md','工作流状态记录.md','交接物字段词典.md');if(-not$isGitRepo){$allowedRootMarkdown+=@('release-check-report.md','field-schema-check-report.md','ci-workflow-check-report.md','alpha-expression-check-report.md','route-schema-check-report.md')};$rootUnexpected=@(Get-ChildItem -LiteralPath $root -Filter '*.md' -File|Where-Object{$allowedRootMarkdown-notcontains$_.Name}|ForEach-Object{$_.Name});Add-DocCheck $checks $errors 'DOC-GOV-005-ROOT-CLEANLINESS' ($rootUnexpected.Count-eq0) ([string]::Join('|',@($rootUnexpected)))

  $linkFiles=if($isGitRepo){@(& git -C $root ls-files 'docs/*.md' 'docs/**/*.md'|Where-Object{$_-notmatch'^docs/tutorials/.+/(accounts|children|parent|checks)/'}|ForEach-Object{Get-Item -LiteralPath (Join-Path $root $_)})}else{@(Get-ChildItem -LiteralPath (Join-Path $root 'docs') -Filter '*.md' -File -Recurse|Where-Object{$_.FullName-notmatch'[\\/]tutorials[\\/].+[\\/](accounts|children|parent|checks)[\\/]'} )};$linkFiles+=@($requiredIndexes|Where-Object{$_-like'*.md'}|ForEach-Object{Get-Item -LiteralPath (Join-Path $root $_)});$linkFiles+=@(Get-Item (Join-Path $root 'README.md'),(Join-Path $root 'PROJECT_MAP.md'),(Join-Path $root 'AGENTS.md'),(Join-Path $root '交接物字段词典.md'),(Join-Path $root 'skills/README.md'),(Join-Path $root 'templates/README.md'),(Join-Path $root 'examples/README.md'));$linkFiles=@($linkFiles|Sort-Object FullName -Unique)
  $broken=[Collections.Generic.List[string]]::new();foreach($file in $linkFiles){$text=Get-Content -LiteralPath $file.FullName -Raw -Encoding UTF8;foreach($match in [regex]::Matches($text,'\[[^\]]*\]\(([^)]+)\)')){$target=$match.Groups[1].Value.Trim().Trim('<','>');if($target-match'^(?:https?:|mailto:|data:)' -or $target-match'\{[^}]+\}'){continue};$parts=$target-split'#',2;$pathPart=[Uri]::UnescapeDataString($parts[0]);$targetFile=if([string]::IsNullOrWhiteSpace($pathPart)){$file.FullName}else{[IO.Path]::GetFullPath((Join-Path $file.DirectoryName $pathPart))};if(-not(Test-Path -LiteralPath $targetFile)){$broken.Add("$($file.FullName.Substring($root.Length+1))=>$target");continue};if($parts.Count-eq2-and-not[string]::IsNullOrWhiteSpace($parts[1])-and[IO.Path]::GetExtension($targetFile)-eq'.md'){$targetText=Get-Content -LiteralPath $targetFile -Raw -Encoding UTF8;$slugs=@([regex]::Matches($targetText,'(?m)^#{1,6}\s+(.+?)\s*$')|ForEach-Object{Get-HeadingSlug $_.Groups[1].Value});if($slugs-notcontains$parts[1].ToLowerInvariant()){$broken.Add("$($file.FullName.Substring($root.Length+1))=>missing_anchor:$target")}}}}
  Add-DocCheck $checks $errors 'DOC-GOV-006-LINKS-AND-ANCHORS' ($broken.Count-eq0) ([string]::Join('|',@($broken)))

  $navDocs=@('docs/product/GitHub开源上线前Workflow修复路线图.md','docs/product/R3-产品总览.md','docs/product/R3-产品确认清单.md','docs/product/R3-画中画与图片资产模型.md','docs/reference/R3-图片资产执行规范.md','交接物字段词典.md');$navMissing=@($navDocs|Where-Object{(Get-Content -LiteralPath (Join-Path $root $_) -TotalCount 80 -Encoding UTF8)-notcontains'<!-- ai-nav:start -->'});Add-DocCheck $checks $errors 'DOC-GOV-007-LONG-DOC-NAV' ($navMissing.Count-eq0) ([string]::Join('|',@($navMissing)))

  $staleFiles=@('docs/product/README.md','docs/product/R3-产品总览.md','docs/product/R3-产品确认清单.md','docs/product/R3-画中画与图片资产模型.md','docs/reference/R3-图片资产执行规范.md');$stale=[Collections.Generic.List[string]]::new();foreach($relative in $staleFiles){$text=Get-Content -LiteralPath (Join-Path $root $relative) -Raw -Encoding UTF8;if(-not$text.Contains('C153')-and-not$text.Contains('C140-C153')){$stale.Add("missing_current_scope:$relative")}};Add-DocCheck $checks $errors 'DOC-GOV-008-CURRENT-SCOPE' ($stale.Count-eq0) ([string]::Join('|',@($stale)))

  $result=if($errors.Count){'fail'}else{'pass'};$report=[ordered]@{schema_id='taoge://reports/docs/governance/v0.1';overall_result=$result;index_count=$requiredIndexes.Count;direct_doc_missing_count=$coverageMissing.Count;broken_link_count=$broken.Count;root_unexpected_count=$rootUnexpected.Count;check_count=$checks.Count;error_count=$errors.Count;checks=[object[]]$checks.ToArray();errors=[object[]]$errors.ToArray()};$fullReport=if([IO.Path]::IsPathRooted($ReportPath)){$ReportPath}else{Join-Path $root $ReportPath};$parent=Split-Path -Parent $fullReport;if(-not(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};[IO.File]::WriteAllText($fullReport,(($report|ConvertTo-Json -Depth 30)+"`n"),[Text.UTF8Encoding]::new($false));Write-Output "DOC_GOVERNANCE_CHECK=$result";Write-Output "CHECK_COUNT=$($checks.Count)";Write-Output "ERROR_COUNT=$($errors.Count)";Write-Output "REPORT=$fullReport";if($errors.Count){exit 1};exit 0
}catch{Write-Error('DOC_GOVERNANCE_ERROR='+$_.Exception.Message);exit 3}
